// Monkey Quest — procedural pixel-art sprites, Game Boy DMG 4-shade palette.
// Each sprite is an array of rows; one character per pixel:
//   '.' or ' ' = transparent
//   'K' = INK   #0f380f (darkest — outlines + deep shadow)
//   'D' = DARK  #306230
//   'M' = MID   #8bac0f
//   'L' = PAPER #e8f8c8 (lightest)
//   'R' = red accent #7a1f1f (eyes, fire, blood, banners)
// Rows may be ragged — the renderer pads short rows with transparency.
// All art is client-owned (pure rendering data); nothing leaves the device.

import { seedFrom } from './dice';

export type SpriteKey = string;

export const SPRITES: Record<SpriteKey, string[]> = {
  // ── Heroes ──────────────────────────────────────────────────────────────
  hero_warrior: [
    '......KRK......',
    '.....KKDKK.....',
    '....KDDDDDK....',
    '....KDLLLDK....',
    '....KDLKLDK....',
    '.....KKKKK.....',
    '..KKKDDDKKK.K..',
    '.KDDDMMMDDDKK..',
    '.KDDDMRMDDDKKK.',
    '.KDDDMMMDDDKK..',
    '..KKDMMMDKK.K..',
    '....KMMMMK.....',
    '....KMK.KMK....',
    '....KDK.KDK....',
    '....KDK.KDK....',
    '...KKKK.KKKK...',
  ],
  hero_ranger: [
    '.....KDDDK.....',
    '....KDDDDDK....',
    '....KDMLMDK....',
    '....KDLKLDK....',
    '.....KDDDK.....',
    '...KKMMMKK.....',
    '..KDMMMMMDK....',
    '..KDMMMMMDK.K..',
    '..KDMLLLMDKKK..',
    '...KMMMMMK.K...',
    '...KMK.KMK.....',
    '...KDK.KDK.....',
    '...KDK.KDK.....',
    '..KKKK.KKKK....',
    '...............',
    '...............',
  ],
  hero_mage: [
    '.......K.......',
    '......KDK......',
    '.....KDDDK.....',
    '....KDDDDDK....',
    '...KKKKKKKKK...',
    '.....KLLLK.....',
    '.....KLKLK.....',
    '......KKK....K.',
    '....KMMMMMK.KK.',
    '...KMMMMMMMKKK.',
    '...KMMLRLMMK.K.',
    '...KMMMMMMMK.K.',
    '....KMMMMMK..K.',
    '....KMK.KMK..K.',
    '....KDK.KDK..K.',
    '...KKK...KKK...',
  ],
  hero_cleric: [
    '.....KLLLK.....',
    '....KLLLLLK....',
    '....KLMLMLK....',
    '....KLLKLLK....',
    '.....KKKK......',
    '....KLLLLLK....',
    '...KLLLRLLLK...',
    '...KLLLRLLLK...',
    '...KLLLRLLLK...',
    '...KLMLLLMLK...',
    '....KLLLLLK....',
    '....KLK.KLK....',
    '....KLK.KLK....',
    '....KDK.KDK....',
    '...KKK...KKK...',
  ],
  hero_paladin: [
    '......KRK......',
    '.....KLLLK.....',
    '....KLLLLLK....',
    '....KLLKLLK....',
    '.....KKKK......',
    '..KKKLLLKKK....',
    '.KLLLLMLLLLK...',
    '.KLLLRMRLLLK...',
    '.KLLLLMLLLLK...',
    '..KKLLLLLKK....',
    '....KLLLK......',
    '....KLK.KLK....',
    '....KDK.KDK....',
    '....KDK.KDK....',
    '...KKKK.KKKK...',
  ],
  hero_barbarian: [
    '....K.K.K.K....',
    '....KDKDKDK....',
    '...KDDDDDDDK...',
    '...KDMLLLMDK...',
    '...KDLKLKLDK...',
    '....KMMMMMK....',
    '...KMMRMRMMK...',
    '..KMMMMMMMMMK..',
    '.KMMMMMMMMMMMK.',
    '.KMMMMMMMMMMMK.',
    '..KMMMMMMMMMK..',
    '...KMMMMMMMK...',
    '....KMK.KMK....',
    '....KDK.KDK....',
    '...KKKK.KKKK...',
  ],
  hero_necromancer: [
    '.......K.......',
    '......KDK......',
    '.....KDDDK.....',
    '....KKKKKKK....',
    '...KDDDDDDDK...',
    '...KKKKKKKKK...',
    '....KRKRKR.....',
    '....KDDDDDK..K.',
    '...KDDDDDDDKKK.',
    '..KDDDRRRDDDKK.',
    '..KDDDRRRDDD.K.',
    '...KDDDDDDDK.K.',
    '....KDDDDDK..K.',
    '....KDK.KDK..K.',
    '...KKK...KKK...',
  ],
  // Rogue — hood pulled low over glinting eyes, a dagger flanking the dark cloak.
  hero_rogue: [
    '.....KKKKK.....',
    '....KDDDDDK....',
    '...KDDDDDDDK...',
    '...KDDKKKDDK...',
    '...KDKRKRKDK...',
    '....KKDDDKK....',
    '..K.KDDDDDK....',
    '..KKMDDDDDMK...',
    '.KK.KDDDDDK.K..',
    '.K..KDDDDDK.KK.',
    '....KDDDDDK..K.',
    '....KMK.KMK....',
    '....KDK.KDK....',
    '....KDK.KDK....',
    '...KKKK.KKKK...',
    '...............',
  ],
  // Druid — antler crown, green robe, a gnarled staff held at the side.
  hero_druid: [
    '...K.K.K.K.K...',
    '...KDK.K.KDK...',
    '....KDDDDDK....',
    '....KDLLLDK....',
    '....KDLKLDK....',
    '.....KKKKK.....',
    '..K.KMMMMMK....',
    '..K.KMMMMMK....',
    '..K.KMMRMMK....',
    '..KKKMMMMMK....',
    '....KMMMMMK....',
    '....KMMMMMK....',
    '....KMK.KMK....',
    '....KDK.KDK....',
    '...KKKK.KKKK...',
    '...............',
  ],
  // Monk — bare shaven head, sashed robe, fists raised in a ready stance.
  hero_monk: [
    '.....KLLLK.....',
    '....KLLLLLK....',
    '....KLLLLLK....',
    '....KLKLKLK....',
    '.....KKKKK.....',
    '...KKMMMMMKK...',
    '..KMMMMMMMMMK..',
    '..KMMMRRRMMMK..',
    '..KMMMMMMMMMK..',
    '..KKMMMMMMMKK..',
    '.K..KMMMMMK..K.',
    '.KK.KMMMMMK.KK.',
    '....KMK.KMK....',
    '....KDK.KDK....',
    '...KKKK.KKKK...',
    '...............',
  ],
  // Bard — feathered cap and a lute slung at the side.
  hero_bard: [
    '........KRK....',
    '......KKKDK....',
    '.....KDDDDDK...',
    '....KDLLLDK....',
    '....KDLKLDK....',
    '.....KKKKK.....',
    '....KMMMMMK.KK.',
    '...KMMMMMMMKDK.',
    '...KMMRMMMMKDK.',
    '...KMMMMMMKKDK.',
    '....KMMMMKDDDK.',
    '....KMMMMMKKK..',
    '....KMK.KMK....',
    '....KDK.KDK....',
    '...KKKK.KKKK...',
    '...............',
  ],

  // ── NPCs (town & world life) ────────────────────────────────────────────
  npc_villager: [
    '......KKK.......',
    '.....KLLLK......',
    '.....KLKLK......',
    '.....KLLLK......',
    '......KKK.......',
    '.....KDDDK......',
    '....KDDDDDK.....',
    '....KDDDDDK.....',
    '....KDMMMDK.....',
    '....KDDDDDK.....',
    '.....KDKDK......',
    '.....KK.KK......',
    '.....KK.KK......',
    '....KKK.KKK.....',
    '................',
  ],
  npc_merchant: [
    '.....KKKKK......',
    '....KMMMMMK.....',
    '.....KLLLK......',
    '.....KLKLK......',
    '......KKK.......',
    '.....KMMMK......',
    '....KMMMMMK.....',
    '....KMLLLMK.....',
    '....KMMMMMK.....',
    '....KMMMMMK.....',
    '.....KMKMK......',
    '.....KK.KK......',
    '.....KK.KK......',
    '....KKK.KKK.....',
    '................',
  ],
  npc_guard: [
    '......KKK.......',
    '.....KMMMK......',
    '.....KLLLK......',
    '.....KLKLK......',
    '......KKK....K..',
    '.....KDDDK...K..',
    '....KDDDDDK..K..',
    '....KDMMMDK..K..',
    '....KDDDDDK..K..',
    '....KDDDDDK..K..',
    '.....KDKDK...K..',
    '.....KK.KK...K..',
    '.....KK.KK...K..',
    '....KKK.KKK..K..',
    '................',
  ],
  npc_elder: [
    '......KKK.......',
    '.....KLLLK......',
    '.....KLKLK......',
    '.....KLLLK......',
    '.....KMMMK......',
    '.....KMMMK......',
    '....KLLLLLK..K..',
    '....KLLLLLK..K..',
    '....KLLLLLK..K..',
    '....KLLLLLK..K..',
    '.....KLKLK...K..',
    '.....KK.KK...K..',
    '.....KK.KK...K..',
    '....KKK.KKK..K..',
    '................',
  ],
  npc_child: [
    '................',
    '................',
    '................',
    '.......KK.......',
    '......KLLK......',
    '......KLKK......',
    '.......KK.......',
    '......KDDK......',
    '.....KDDDK......',
    '.....KDDDK......',
    '......KDK.......',
    '......K.K.......',
    '......K.K.......',
    '.....KK.KK......',
    '................',
  ],

  // ── Enemies ─────────────────────────────────────────────────────────────
  foe_skeleton: [
    '......KKK.......',
    '.....KLLLK......',
    '.....KKLKK......',
    '.....KLKLK......',
    '......KLK.......',
    '......KKK.......',
    '.....LKLKL......',
    '....KLKLKLK....',
    '.....KLLLK......',
    '.....KLKLK......',
    '.....KLKLK......',
    '.....KK.KK......',
    '.....KK.KK......',
    '....KKK.KKK.....',
    '................',
  ],
  foe_wolf: [
    '................',
    '................',
    '.KK........KK...',
    'KMMK.....KKMMK..',
    'KMMMK..KMMMMMK..',
    '.KMMMMMMMMMMMK..',
    '.KMRMMMMMMMMMK..',
    '..KMMMMMMMMMMK..',
    '..KMMMMMMMMMMK..',
    '..KK.KK.KK.KK...',
    '..K..K..K..K....',
    '................',
    '................',
  ],
  foe_spider: [
    '................',
    '..K..........K..',
    '..KK..KKKK..KK..',
    '...KKKDDDDKKK...',
    '..KKDDDDDDDDKK..',
    '.K.KDDRDDRDDK.K.',
    '.K.KDDDDDDDDK.K.',
    '..K.KDDDDDDK.K..',
    '...KK.KDDK.KK...',
    '..K....KK....K..',
    '................',
  ],
  foe_troll: [
    '.....KKKK.......',
    '....KMMMMK......',
    '...KMMMMMMK.....',
    '...KMRMMRMK.....',
    '...KMMMMMMK.....',
    '...KMLMMLMK.....',
    '....KMMMMK......',
    '..KKMMMMMMKK....',
    '.KMMMMMMMMMMK...',
    '.KMMMMMMMMMMK...',
    '.KMMDMMMMDMMK...',
    '..KMMMK.KMMMK...',
    '..KKKK...KKKK...',
    '................',
  ],
  foe_bandit: [
    '......KKK.......',
    '.....KDDDK......',
    '.....KLLLK......',
    '.....KKKKK......',
    '.....KLKLK......',
    '......KKK.......',
    '.....KDDDK...K..',
    '....KDDDDDK.KK..',
    '....KDMMMDK..K..',
    '....KDDDDDK..K..',
    '.....KDKDK......',
    '.....KK.KK......',
    '.....KK.KK......',
    '....KKK.KKK.....',
    '................',
  ],
  foe_bat: [
    '................',
    '................',
    '.KK........KK...',
    'KMMKK....KKMMK..',
    'KMMMMK..KMMMMK..',
    'KMMMMMKKMMMMMK..',
    '.KMMMRMMRMMMK...',
    '..KMMMMMMMMK....',
    '...KMMMMMMK.....',
    '....KK..KK......',
    '................',
  ],
  foe_slime: [
    '................',
    '................',
    '......KKKK......',
    '....KKMMMMKK....',
    '...KMMMMMMMMK...',
    '..KMLLMMMMMMK...',
    '..KMMMMMMMMMK...',
    '..KMMRMMMMRMK...',
    '..KMMMMMMMMMK...',
    '..KMMMMMMMMMK...',
    '.KMMMMMMMMMMMK..',
    '.KKKKKKKKKKKKK..',
    '................',
  ],
  foe_ghost: [
    '................',
    '......KKKK......',
    '....KKLLLLKK....',
    '...KLLLLLLLLK...',
    '..KLLKKLLKKLLK..',
    '..KLLLLLLLLLLK..',
    '..KLLLLLLLLLLK..',
    '..KLLLLLLLLLLK..',
    '..KLLLLLLLLLLK..',
    '..KLLLLLLLLLLK..',
    '..KLKLKLKLKLK...',
    '...K.K.K.K.K....',
    '................',
  ],
  foe_golem: [
    '....KKKKKK......',
    '...KMMMMMMK.....',
    '...KMRMMRMK.....',
    '...KMMMMMMK.....',
    '..KKMMMMMMKK....',
    '.KMMMMMMMMMMK...',
    '.KMMKMMMMKMMK...',
    '.KMMMMMMMMMMK...',
    '.KMMMMMMMMMMK...',
    '.KMKMMMMMMKMK...',
    '.KMKMMMMMMKMK...',
    '..KK.KKKK.KK....',
    '..KK......KK....',
    '................',
  ],
  foe_serpent: [
    '................',
    '.....KKKK.......',
    '...KKMMMMKK.....',
    '..KMMRRMMMK.....',
    '..KMMMMMMMK.R...',
    '..KMMKKMMMKKK...',
    '...KMMMMMMMMK...',
    '....KKMMMMMK....',
    '..KMMMMMMMK.....',
    '.KMMMMMKKMMK....',
    '.KMMMMK..KMMK...',
    '..KKKK....KK....',
    '................',
  ],
  foe_imp: [
    '................',
    '..K.......K.....',
    '..KK.....KK.....',
    '..KRKKKKKRK.....',
    '.KRRRRRRRRRK....',
    '.KRRKRRKRRRK....',
    '.KRRRRRRRRRK....',
    '..KRRRRRRRK.....',
    '...KRRRRRK.K....',
    '...KRK.KRK.KK...',
    '...KK...KK..K...',
    '................',
  ],
  foe_cultist: [
    '.....KKKK.......',
    '....KDDDDK......',
    '...KDDDDDDK.....',
    '...KDKKKKDK.....',
    '...KDKKKKDK.....',
    '...KDDDDDDK.....',
    '..KDDDDDDDDK....',
    '..KDDDRDDDDK....',
    '..KDDDDDDDDK....',
    '..KDDDDDDDDK....',
    '..KDDDDDDDDK....',
    '...KDK..KDK.....',
    '...KK....KK.....',
    '................',
  ],
  foe_mimic: [
    '................',
    '..KKKKKKKKKK....',
    '.KDDDDDDDDDDK...',
    '.KDMMMMMMMMDK...',
    '.KDDDDDDDDDDK...',
    '.KLKLKLKLKLLK...',
    '.KDRRRRRRRRDK...',
    '.KLKLKLKLKLLK...',
    '.KDDDDMDDDDDK...',
    '.KDDDDMDDDDDK...',
    '.KKKKKKKKKKKK...',
    '..K........K....',
    '................',
  ],

  // ── Environment props ───────────────────────────────────────────────────
  prop_house: [
    '......KKKK......',
    '.....KDDDDK.....',
    '....KDDDDDDK....',
    '...KDDDDDDDDK...',
    '..KDDDDDDDDDDK..',
    '.KKKKKKKKKKKKK..',
    '.KLLLLLLLLLLLK..',
    '.KLLKMMKLLLLLK..',
    '.KLLKMMKLLLLLK..',
    '.KLLLLLLLKKKLK..',
    '.KLLLLLLLKLKLK..',
    '.KLLLLLLLKLKLK..',
    '.KKKKKKKKKKKKK..',
    '................',
  ],
  prop_tower: [
    '.....KKK........',
    '.....KRRK.......',
    '.....KK.K.......',
    '....KKKKKK......',
    '....KDLLLDK.....',
    '....KDLMLDK.....',
    '....KDLLLDK.....',
    '....KDLLLDK.....',
    '....KKKKKKK.....',
    '...KDLLLLLDK....',
    '...KDLLMMLDK....',
    '...KDLLMMLDK....',
    '...KKKKKKKKK....',
    '................',
  ],
  prop_tree: [
    '.....KKKKK......',
    '...KKMMMMMKK....',
    '..KMMMMMMMMMK...',
    '.KMMMDDMMMMMK...',
    '.KMMMMMMMMDMK...',
    '.KMDMMMMMMMMK...',
    '.KMMMMMDDMMMK...',
    '..KMMMMMMMMK....',
    '...KKMMMMKK.....',
    '.....KDDK.......',
    '......KDK.......',
    '......KDK.......',
    '.....KDDK.......',
    '....KKKKKK......',
  ],
  prop_pine: [
    '.......KK.......',
    '......KMMK......',
    '......KMMK......',
    '.....KMMMMK.....',
    '....KMDDMMK.....',
    '....KMMMMMMK....',
    '...KMDDMMMMK....',
    '...KMMMMMMMK....',
    '..KMDDMMMMMMK...',
    '..KMMMMMMMMMK...',
    '.KMMMMMMMMMMMK..',
    '.KMMDDMMMMMMMK..',
    '......KDK.......',
    '......KDK.......',
  ],
  prop_rock: [
    '................',
    '.....KKKK.......',
    '...KKMMMDK......',
    '..KMMMMMMDK.....',
    '.KMMMLMMMMDK....',
    '.KMMMMMMMDDK....',
    '.KMMMMMDDDK.....',
    '..KKKKKKKK......',
    '................',
  ],
  prop_pillar: [
    '.....KKKK.......',
    '....KLLLLK......',
    '....KLMMLK......',
    '.....KMMK.......',
    '.....KLMK.......',
    '.....KMLK.......',
    '.....KLMK.......',
    '.....KMLK.......',
    '.....KLMK.......',
    '.....KMLK.......',
    '....KKMMKK......',
    '...KLLLLLLK.....',
    '...KKKKKKKK.....',
    '................',
  ],
  prop_tomb: [
    '................',
    '.....KKKK.......',
    '....KDDDDK......',
    '...KDLLLLDK.....',
    '...KDLKKLDK.....',
    '...KDLLLLDK.....',
    '...KDLKKLDK.....',
    '...KDLLLLDK.....',
    '...KDDDDDDK.....',
    '..KMMMMMMMMK....',
    '.KMMMMMMMMMMK...',
    '................',
  ],
  prop_fire: [
    '................',
    '.......R........',
    '......RRR.......',
    '......RLR.......',
    '.....RRLRR......',
    '.....RLLLR......',
    '....RRLLLRR.....',
    '....RRLLLRR.....',
    '...KKDDMDDKK....',
    '..KDDDDDDDDDK...',
    '................',
  ],
  prop_well: [
    '......KKKK......',
    '.....KDDDDK.....',
    '....KDDDDDDK....',
    '....KK....KK....',
    '...KKLLLLLLKK...',
    '...KLMMMMMMLK...',
    '...KLMMMMMMLK...',
    '...KLLLLLLLLK...',
    '...KKKKKKKKKK...',
    '................',
  ],
  prop_banner: [
    '.....KKKK..K....',
    '.....KRRK..K....',
    '.....KRRK..K....',
    '.....KRRK..K....',
    '.....KK.K..K....',
    '........K..K....',
    '........K..K....',
    '........KKKK....',
    '................',
  ],
  prop_tent: [
    '................',
    '.......K........',
    '......KMK.......',
    '.....KMMMK......',
    '....KMDMMK......',
    '...KMMDMMMK.....',
    '..KMMMDMMMMK....',
    '.KMMMMDMKMMMK...',
    '.KMMMMDMKMMMK...',
    '.KMMMMDMKMMMK...',
    '.KKKKKKKKKKKK...',
    '................',
  ],
  prop_crystal: [
    '................',
    '.......K........',
    '......KLK.......',
    '......KLK.......',
    '.....KLMLK......',
    '.....KLMLK......',
    '....KLMMMLK.....',
    '....KLMDMLK.....',
    '....KLMMMLK.....',
    '.....KLMLK......',
    '...K..KLK..K....',
    '..KLK.KLK.KLK...',
    '..KKK.KKK.KKK...',
    '................',
  ],
  prop_mushroom: [
    '................',
    '....KKKKKK......',
    '..KKRRRRRRKK....',
    '.KRLRRRRRLRRK...',
    '.KRRRRRRRRRRK...',
    '..KKRRRRRRKK....',
    '....KMMMMK......',
    '....KMMMMK......',
    '....KMDMMK......',
    '...KKMMMKK......',
    '................',
  ],
  prop_statue: [
    '.....KKKK.......',
    '....KLLLLK......',
    '....KLDDLK......',
    '....KLLLLK......',
    '.....KLLK.......',
    '...KKLLLLKK.....',
    '..KLLLLLLLLK....',
    '..KLLDDDDLLK....',
    '..KLLLLLLLLK....',
    '...KLLLLLLK.....',
    '....KLLLLK......',
    '...KKLLLLKK.....',
    '..KKKKKKKKKK....',
    '................',
  ],
  prop_chest: [
    '................',
    '................',
    '...KKKKKKKK.....',
    '..KMLLLLLLMK....',
    '..KMDDDDDDMK....',
    '..KLLLLLLLLK....',
    '..KMMMRMMMMK....',
    '..KMMMRMMMMK....',
    '..KLLLLLLLLK....',
    '..KKKKKKKKKK....',
    '................',
  ],
  prop_bush: [
    '................',
    '................',
    '.....KKKK.......',
    '...KKMMMMKK.....',
    '..KMMMDMMMMK....',
    '.KMMMMMMMDMK....',
    '.KMDMMMMMMMK....',
    '..KKMMMMMKK.....',
    '....KKKKK.......',
    '................',
  ],
  prop_stalagmite: [
    '................',
    '.......K........',
    '.......K........',
    '......KMK.......',
    '......KMK.......',
    '.....KMDK.......',
    '....KMMMK.......',
    '....KMMMMK......',
    '...KMMDMMK......',
    '...KMMMMMK......',
    '..KMMMMMMMK.....',
    '..KKKKKKKKK.....',
    '................',
  ],
  prop_mountain: [
    '................',
    '......KK........',
    '.....KLLK.......',
    '....KLMMLK.KK...',
    '...KLMMMMLKLLK..',
    '..KLMMMMMMLMMLK.',
    '.KLMMMMMMMMMMMLK',
    'KLMMMMMMMMMMMMML',
    'KMMMMMMMMMMMMMMM',
  ],
  prop_signpost: [
    '................',
    '......K.........',
    '...KKKKKKK......',
    '...KLLLLLK......',
    '...KKKKKKK......',
    '......K.........',
    '....KKKKKK......',
    '....KLLLLK......',
    '....KKKKKK......',
    '......K.........',
    '......K.........',
    '......K.........',
    '................',
  ],
  prop_cactus: [
    '................',
    '......K.........',
    '.....KMK........',
    '..K..KMK........',
    '.KMK.KMK..K.....',
    '.KMK.KMK.KMK....',
    '.KMKKKMKKKMK....',
    '..KMMMMMMMK.....',
    '....KMDMK.......',
    '....KMMMK.......',
    '...KKMMMKK......',
    '................',
  ],
  prop_barrel: [
    '................',
    '....KKKKKK......',
    '...KLMMMMLK.....',
    '...KMDDDDMK.....',
    '...KLMMMMLK.....',
    '...KMDDDDMK.....',
    '...KLMMMMLK.....',
    '...KKKKKKKK.....',
    '................',
  ],

  // ── Map terrain tiles ─────────────────────────────────────────────────────
  // Small motifs scattered across the world-map biomes (see BIOMES in
  // RpgConsole). Kept tiny + low-contrast so they read as ground texture, not
  // foreground props.
  map_grass: [
    '.......',
    '..K.K..',
    '.KMKMK.',
    'KMKKKMK',
    '..KKK..',
  ],
  map_tree: [
    '..KKK..',
    '.KMMMK.',
    'KMMDMMK',
    'KMMMMMK',
    '.KMMMK.',
    '...K...',
    '..KKK..',
  ],
  map_pine: [
    '...K...',
    '..KMK..',
    '.KMMMK.',
    'KMDMMMK',
    '.KMMMK.',
    '...K...',
    '..KKK..',
  ],
  map_rock: [
    '.......',
    '..KKK..',
    '.KMMDK.',
    'KMMMDDK',
    '.KKKKK.',
  ],
  map_cobble: [
    'KK.KK.KK',
    '.K..K..K',
    'KK.KK.KK',
    '.K..K..K',
  ],
  map_rubble: [
    '.......',
    'K.KK.K.',
    'KKMMKKK',
    'KKKKKKK',
  ],
  map_bone: [
    '.KKKK.',
    'KLLLLK',
    'KLKLKL',
    '.KLLK.',
    '.K..K.',
  ],
  map_crack: [
    '........',
    '..K.....',
    '.K.KKK..',
    'K....K.K',
    '......K.',
  ],

  // ── Relief & extra biome tiles (mountains, hills, water, plains, marsh) ─────
  map_mountain: [
    '....K....',
    '...KLK...',
    '..KLLLK..',
    '.KMLLLMK.',
    'KMMMLMMMK',
    'KMMMMMMMK',
    'KKKKKKKKK',
  ],
  map_hill: [
    '..KKKK...',
    '.KMMMMK..',
    'KMMMMMMK.',
    'KKKKKKKKK',
  ],
  map_water: [
    '.........',
    'KK..KKK..',
    '..KK...KK',
    'KK..KKK..',
    '.........',
  ],
  map_reed: [
    '.K...K.K.',
    '.K.K.K.K.',
    'KK.K.KKKK',
    '.KKKKK.K.',
  ],
  map_flower: [
    '..K...K..',
    '.KLK.KMK.',
    '..K...K..',
    'K..K.K..K',
    '.KK.K.KK.',
  ],
  map_dune: [
    '.........',
    '..KKK....',
    'KK...KKKK',
    'KKKKKKKKK',
  ],
  map_snow: [
    'K...K..K.',
    '..K...K..',
    '.K..K...K',
    'K...K.K..',
  ],

  // ── Map critters ──────────────────────────────────────────────────────────
  // Tiny creatures that wander the world map: road traffic moving city-to-city
  // (traveler / cart / horse) and wild fauna roaming the biomes. Drawn at ~1.4px
  // so they read as little dots of life, never foreground.
  crit_traveler: [
    '.K..',
    'KKK.',
    '.KK.',
    '.K..',
    'K.K.',
  ],
  crit_cart: [
    '..MM...',
    '.MMMM..',
    'KKKKKKK',
    '.K...K.',
  ],
  crit_horse: [
    '.....K',
    '..MMKK',
    '.MMMM.',
    'MMMMM.',
    '.K..K.',
  ],
  crit_deer: [
    'K...K.',
    '.MMM..',
    '..M...',
    '.MMMM.',
    'MMMMMK',
    '.K..K.',
  ],
  crit_boar: [
    '.MMMM.',
    'MMMMMM',
    'KMMMMK',
    '.K..K.',
  ],
  crit_rabbit: [
    'K.K.',
    'KKK.',
    'KMMK',
    '.KK.',
  ],
  crit_bird: [
    'M.M',
    '.M.',
  ],
  crit_snake: [
    'KK...',
    '.MMK.',
    '...KK',
  ],
  crit_rat: [
    '.....',
    'MMMMK',
    'K..K.',
  ],
  crit_bat: [
    'K.K.K',
    'KMMMK',
    '.K.K.',
  ],

  // ── Peoples (faction emblems for the destination board) ───────────────────
  // 14x14 heraldic shields; the culture motif sits in rows 3-5, the rest is a
  // shared shield frame. Identity comes from the motif shape + the per-people
  // palette below (each shield reads distinct on every theme). Pure data.
  people_highland: [
    '.KKKKKKKKKKKK.',
    'KLLLLLLLLLLLLK',
    'KMMMMMMMMMMMMK',
    'KMMMMMLLMMMMMK',
    'KMMMMLLLLMMMMK',
    'KMMMLLLLLLMMMK',
    'KMMMMMMMMMMMMK',
    'KDMMMMMMMMMMDK',
    '.KDMMMMMMMMDK.',
    '..KDMMMMMMDK..',
    '...KDMMMMDK...',
    '....KDMMDK....',
    '.....KDDK.....',
    '......KK......',
  ],
  people_rivers: [
    '.KKKKKKKKKKKK.',
    'KLLLLLLLLLLLLK',
    'KMMMMMMMMMMMMK',
    'KMLLMMLLMMLLMK',
    'KMMLLMMLLMMLMK',
    'KMMMLLMMLLMMMK',
    'KMMMMMMMMMMMMK',
    'KDMMMMMMMMMMDK',
    '.KDMMMMMMMMDK.',
    '..KDMMMMMMDK..',
    '...KDMMMMDK...',
    '....KDMMDK....',
    '.....KDDK.....',
    '......KK......',
  ],
  people_dunes: [
    '.KKKKKKKKKKKK.',
    'KLLLLLLLLLLLLK',
    'KMMMMMMMMMMMMK',
    'KMMMMLLLLMMMMK',
    'KMMMLLLLLLMMMK',
    'KMMMMLLLLMMMMK',
    'KMMMMMMMMMMMMK',
    'KDMMMMMMMMMMDK',
    '.KDMMMMMMMMDK.',
    '..KDMMMMMMDK..',
    '...KDMMMMDK...',
    '....KDMMDK....',
    '.....KDDK.....',
    '......KK......',
  ],
  people_mire: [
    '.KKKKKKKKKKKK.',
    'KLLLLLLLLLLLLK',
    'KMMMMMMMMMMMMK',
    'KMMLMMLMMLMMMK',
    'KMMLMMLMMLMMMK',
    'KMMLMMLMMLMMMK',
    'KMMMMMMMMMMMMK',
    'KDMMMMMMMMMMDK',
    '.KDMMMMMMMMDK.',
    '..KDMMMMMMDK..',
    '...KDMMMMDK...',
    '....KDMMDK....',
    '.....KDDK.....',
    '......KK......',
  ],
  people_forge: [
    '.KKKKKKKKKKKK.',
    'KLLLLLLLLLLLLK',
    'KMMMMMMMMMMMMK',
    'KMMLLLLLLLMMMK',
    'KMMMMLLLMMMMMK',
    'KMMMLLLLLMMMMK',
    'KMMMMMMMMMMMMK',
    'KDMMMMMMMMMMDK',
    '.KDMMMMMMMMDK.',
    '..KDMMMMMMDK..',
    '...KDMMMMDK...',
    '....KDMMDK....',
    '.....KDDK.....',
    '......KK......',
  ],
  people_pilgrims: [
    '.KKKKKKKKKKKK.',
    'KLLLLLLLLLLLLK',
    'KMMMMMMMMMMMMK',
    'KMMMMMLLMMMMMK',
    'KMMLLLLLLLLMMK',
    'KMMMMMLLMMMMMK',
    'KMMMMMMMMMMMMK',
    'KDMMMMMMMMMMDK',
    '.KDMMMMMMMMDK.',
    '..KDMMMMMMDK..',
    '...KDMMMMDK...',
    '....KDMMDK....',
    '.....KDDK.....',
    '......KK......',
  ],
  people_steppe: [
    '.KKKKKKKKKKKK.',
    'KLLLLLLLLLLLLK',
    'KMMMMMMMMMMMMK',
    'KMMLLLLLLLLMMK',
    'KMMMMMMMMMMMMK',
    'KMMLLLLLLLLMMK',
    'KMMMMMMMMMMMMK',
    'KDMMMMMMMMMMDK',
    '.KDMMMMMMMMDK.',
    '..KDMMMMMMDK..',
    '...KDMMMMDK...',
    '....KDMMDK....',
    '.....KDDK.....',
    '......KK......',
  ],
  people_coast: [
    '.KKKKKKKKKKKK.',
    'KLLLLLLLLLLLLK',
    'KMMMMMMMMMMMMK',
    'KMMMMMLLMMMMMK',
    'KMMMLLLLLLMMMK',
    'KMMMMMLLMMMMMK',
    'KMMMMMMMMMMMMK',
    'KDMMMMMMMMMMDK',
    '.KDMMMMMMMMDK.',
    '..KDMMMMMMDK..',
    '...KDMMMMDK...',
    '....KDMMDK....',
    '.....KDDK.....',
    '......KK......',
  ],
  people_canopy: [
    '.KKKKKKKKKKKK.',
    'KLLLLLLLLLLLLK',
    'KMMMMMMMMMMMMK',
    'KMMMMMRRMMMMMK',
    'KMMMRRLLRRMMMK',
    'KMMRRLLLLRRMMK',
    'KMMMMMMMMMMMMK',
    'KDMMMMMMMMMMDK',
    '.KDMMMMMMMMDK.',
    '..KDMMMMMMDK..',
    '...KDMMMMDK...',
    '....KDMMDK....',
    '.....KDDK.....',
    '......KK......',
  ],
  people_frost: [
    '.KKKKKKKKKKKK.',
    'KLLLLLLLLLLLLK',
    'KMMMMMMMMMMMMK',
    'KMMRMMMLMMRMMK',
    'KMMMRLLLLRMMMK',
    'KMMRMMMLMMRMMK',
    'KMMMMMMMMMMMMK',
    'KDMMMMMMMMMMDK',
    '.KDMMMMMMMMDK.',
    '..KDMMMMMMDK..',
    '...KDMMMMDK...',
    '....KDMMDK....',
    '.....KDDK.....',
    '......KK......',
  ],
  people_ash: [
    '.KKKKKKKKKKKK.',
    'KLLLLLLLLLLLLK',
    'KMMMMMMMMMMMMK',
    'KMMMMMLRMMMMMK',
    'KMMMMLRRLMMMMK',
    'KMMMLLRRLLMMMK',
    'KMMMMMMMMMMMMK',
    'KDMMMMMMMMMMDK',
    '.KDMMMMMMMMDK.',
    '..KDMMMMMMDK..',
    '...KDMMMMDK...',
    '....KDMMDK....',
    '.....KDDK.....',
    '......KK......',
  ],
  people_veld: [
    '.KKKKKKKKKKKK.',
    'KLLLLLLLLLLLLK',
    'KMMMMMMMMMMMMK',
    'KMRMMMRRMMMRMK',
    'KMRRMLLLLMRRMK',
    'KMRMMMRRMMMRMK',
    'KMMMMMMMMMMMMK',
    'KDMMMMMMMMMMDK',
    '.KDMMMMMMMMDK.',
    '..KDMMMMMMDK..',
    '...KDMMMMDK...',
    '....KDMMDK....',
    '.....KDDK.....',
    '......KK......',
  ],
  people_delvers: [
    '.KKKKKKKKKKKK.',
    'KLLLLLLLLLLLLK',
    'KMMMMMMMMMMMMK',
    'KRMMMMMMMMMMRK',
    'KMRMMMMMMMMRMK',
    'KMMMRRMMRRMMMK',
    'KMMMMMMMMMMMMK',
    'KDMMMMMMMMMMDK',
    '.KDMMMMMMMMDK.',
    '..KDMMMMMMDK..',
    '...KDMMMMDK...',
    '....KDMMDK....',
    '.....KDDK.....',
    '......KK......',
  ],
  people_orchard: [
    '.KKKKKKKKKKKK.',
    'KLLLLLLLLLLLLK',
    'KMMMMMMMMMMMMK',
    'KMMMMRRRRMMMMK',
    'KMMMRRRRRRMMMK',
    'KMMMMMDDMMMMMK',
    'KMMMMMMMMMMMMK',
    'KDMMMMMMMMMMDK',
    '.KDMMMMMMMMDK.',
    '..KDMMMMMMDK..',
    '...KDMMMMDK...',
    '....KDMMDK....',
    '.....KDDK.....',
    '......KK......',
  ],

  // ── Explorer clubs (hub crests) ───────────────────────────────────────────
  // Same shield frame as the peoples; the motif is each club's signature device
  // (compass rose / crossed blades / arcane eye). Identity via motif + palette.
  club_pathfinders: [
    '.KKKKKKKKKKKK.',
    'KLLLLLLLLLLLLK',
    'KMMMMMMMMMMMMK',
    'KMMLMMLLMMLMMK',
    'KMMMLLLLLLMMMK',
    'KMMLMMLLMMLMMK',
    'KMMMMMMMMMMMMK',
    'KDMMMMMMMMMMDK',
    '.KDMMMMMMMMDK.',
    '..KDMMMMMMDK..',
    '...KDMMMMDK...',
    '....KDMMDK....',
    '.....KDDK.....',
    '......KK......',
  ],
  club_armorers: [
    '.KKKKKKKKKKKK.',
    'KLLLLLLLLLLLLK',
    'KMMMMMMMMMMMMK',
    'KMMLMMMMMMLMMK',
    'KMMMLLLLLLMMMK',
    'KMMLMMMMMMLMMK',
    'KMMMMMMMMMMMMK',
    'KDMMMMMMMMMMDK',
    '.KDMMMMMMMMDK.',
    '..KDMMMMMMDK..',
    '...KDMMMMDK...',
    '....KDMMDK....',
    '.....KDDK.....',
    '......KK......',
  ],
  club_mystics: [
    '.KKKKKKKKKKKK.',
    'KLLLLLLLLLLLLK',
    'KMMMMMMMMMMMMK',
    'KMMMLLLLLLMMMK',
    'KMMLLLRRLLLMMK',
    'KMMMLLLLLLMMMK',
    'KMMMMMMMMMMMMK',
    'KDMMMMMMMMMMDK',
    '.KDMMMMMMMMDK.',
    '..KDMMMMMMDK..',
    '...KDMMMMDK...',
    '....KDMMDK....',
    '.....KDDK.....',
    '......KK......',
  ],
};

// ── Colour palettes (per sprite family) ─────────────────────────────────────
// Rich colours layered over the DMG ramp at render time: the renderer merges
// these over PixelSprite's DEFAULT_PALETTE, so any key without an entry keeps
// the theme look (map tiles + critters stay low-contrast ground texture on
// purpose). A shared warm-dark outline replaces the theme ink so the colours
// pop on every theme. Pure data, client-owned.
const OUT = '#2b2016'; // warm near-black outline
const SKIN = '#efc9a3';

export const SPRITE_PALETTES: Record<SpriteKey, Record<string, string>> = {
  // Heroes
  hero_warrior: { K: OUT, D: '#566576', M: '#90a2b8', L: SKIN, R: '#b8362b' },
  hero_ranger: { K: OUT, D: '#3d5a2e', M: '#7c9d4e', L: SKIN, R: '#8a6a42' },
  hero_mage: { K: OUT, D: '#36286b', M: '#6a55ad', L: '#f0e8d6', R: '#e0b53a' },
  hero_cleric: { K: OUT, D: '#8a6a42', M: '#d6b23a', L: '#f5edda', R: '#b8362b' },
  hero_paladin: { K: OUT, D: '#8a99ad', M: '#e0bb3c', L: '#e6eaf0', R: '#b8362b' },
  hero_barbarian: { K: OUT, D: '#5f3a22', M: '#d09a68', L: '#f3d3ad', R: '#9a2e22' },
  hero_necromancer: { K: OUT, D: '#2e2842', M: '#4c4470', L: '#cdbfe2', R: '#a23fce' },
  hero_rogue: { K: OUT, D: '#3c3540', M: '#6b5f4a', L: SKIN, R: '#d6c23a' },
  hero_druid: { K: OUT, D: '#3a5a2e', M: '#6e9a4a', L: SKIN, R: '#c0432e' },
  hero_monk: { K: OUT, D: '#8a5a2a', M: '#d68a3a', L: SKIN, R: '#b8362b' },
  hero_bard: { K: OUT, D: '#6b4226', M: '#3a8a8a', L: SKIN, R: '#d6483a' },
  // NPCs
  npc_villager: { K: OUT, D: '#8a6a42', M: '#5d7a3a', L: SKIN },
  npc_merchant: { K: OUT, D: '#5f3f22', M: '#7a4a9c', L: SKIN },
  npc_guard: { K: OUT, D: '#5d6b7d', M: '#9aa6b5', L: SKIN },
  npc_elder: { K: OUT, D: '#7d7668', M: '#7a8a9a', L: '#e8e2d2' },
  npc_child: { K: OUT, D: '#3e6da5', M: '#5d7a3a', L: SKIN },
  // Foes
  foe_skeleton: { K: OUT, D: '#7d7668', M: '#9a9388', L: '#e9e4d2' },
  foe_wolf: { K: OUT, D: '#564538', M: '#8a7a64', L: '#cfc8b4', R: '#d03828' },
  foe_spider: { K: OUT, D: '#3c2f28', M: '#6e675c', R: '#d03828' },
  foe_troll: { K: OUT, D: '#4c6b38', M: '#6f8f4e', L: '#e9e4d2', R: '#d03828' },
  foe_bandit: { K: OUT, D: '#564538', M: '#7d5f3f', L: SKIN },
  foe_bat: { K: OUT, D: '#46355c', M: '#5f4a6d', R: '#d03828' },
  foe_slime: { K: OUT, D: '#33682c', M: '#4fa05c', L: '#a9e2a2', R: '#d03828' },
  foe_ghost: { K: OUT, D: '#7a8a9a', M: '#a9bcc6', L: '#cfdfe8' },
  foe_golem: { K: OUT, D: '#6e675c', M: '#8d8678', L: '#cfc8b4', R: '#d08a28' },
  foe_serpent: { K: OUT, D: '#33682c', M: '#4f8f5c', L: '#a9e2a2', R: '#d03828' },
  foe_imp: { K: OUT, D: '#5a1f1a', M: '#8a3a2a', R: '#c03028' },
  foe_cultist: { K: OUT, D: '#46235c', M: '#5d4a9c', L: '#dcd7e8', R: '#c03028' },
  foe_mimic: { K: OUT, D: '#6b4a2a', M: '#8d5f35', L: '#efe7d4', R: '#c03028' },
  // Props
  prop_house: { K: OUT, D: '#9d4a32', M: '#6b8fb5', L: '#ecdfbd' },
  prop_tower: { K: OUT, D: '#7d7668', M: '#6b8fb5', L: '#cfc8b4', R: '#c03028' },
  prop_tree: { K: OUT, D: '#5f4226', M: '#4f8f3e', L: '#a9e2a2' },
  prop_pine: { K: OUT, D: '#2c5a38', M: '#3f7a4a', L: '#a9e2a2' },
  prop_bush: { K: OUT, D: '#33682c', M: '#4f8f3e', L: '#a9e2a2' },
  prop_rock: { K: OUT, D: '#6e675c', M: '#9a9388', L: '#cfc8b4' },
  prop_stalagmite: { K: OUT, D: '#6e6780', M: '#9a93a8', L: '#d8d2e0' },
  prop_pillar: { K: OUT, D: '#8a8478', M: '#aaa492', L: '#d8d2c0' },
  prop_tomb: { K: OUT, D: '#7d7668', M: '#5d7a3a', L: '#d8d2c0' },
  prop_fire: { K: OUT, D: '#5a3a20', M: '#8d5f35', L: '#f5c83f', R: '#e2581f' },
  prop_well: { K: OUT, D: '#8a6a42', M: '#4f7ab5', L: '#cfc8b4' },
  prop_banner: { K: OUT, D: '#8a6a42', M: '#8d5f35', R: '#c03028' },
  prop_tent: { K: OUT, D: '#8a6a3a', M: '#b08d57', L: '#efe7d4' },
  prop_crystal: { K: OUT, D: '#3a8aa8', M: '#6bc0d8', L: '#bfe6f0' },
  prop_mushroom: { K: OUT, D: '#8a7a5a', M: '#cfc09a', L: '#efe7d4', R: '#c03028' },
  prop_statue: { K: OUT, D: '#8a8478', M: '#aaa492', L: '#d8d2c0' },
  prop_chest: { K: OUT, D: '#5f3f22', M: '#8d5f35', L: '#e0b341', R: '#c03028' },
  prop_barrel: { K: OUT, D: '#5f3f22', M: '#8d5f35', L: '#c0b08a' },
  prop_signpost: { K: OUT, D: '#8a6a42', M: '#8d5f35', L: '#d8b87a' },
  prop_cactus: { K: OUT, D: '#33682c', M: '#4f9a4e', L: '#a9e2a2' },
  prop_mountain: { K: OUT, D: '#6e675c', M: '#8d8678', L: '#f0efe8' },
  // Peoples — one signature hue per culture so each shield reads at a glance.
  people_highland: { K: OUT, D: '#4a5560', M: '#7d8a96', L: '#e6eaf0' },
  people_rivers: { K: OUT, D: '#1f5a6a', M: '#3a8aa0', L: '#bfe6f0' },
  people_dunes: { K: OUT, D: '#9a6a2a', M: '#d6a64a', L: '#f5e3a8' },
  people_mire: { K: OUT, D: '#2e4a2a', M: '#4f6e3a', L: '#9ad06a' },
  people_forge: { K: OUT, D: '#4a3026', M: '#8a4a30', L: '#f5a84a' },
  people_pilgrims: { K: OUT, D: '#46357c', M: '#7a6ab0', L: '#f0e8d6' },
  people_steppe: { K: OUT, D: '#7a6a2a', M: '#b0a04a', L: '#f0e3a0' },
  people_coast: { K: OUT, D: '#2a4a8a', M: '#4a78c0', L: '#cfe0f5' },
  people_canopy: { K: OUT, D: '#1f5a35', M: '#2f8a52', L: '#bff0c8', R: '#e8d24a' },
  people_frost: { K: OUT, D: '#3a6a8a', M: '#6aa0c0', L: '#e8f4fa', R: '#bfe0f0' },
  people_ash: { K: OUT, D: '#3a3338', M: '#6a5f66', L: '#cfc6cc', R: '#e0552a' },
  people_veld: { K: OUT, D: '#8a6a1f', M: '#c0992f', L: '#f5e6a0', R: '#e07a2a' },
  people_delvers: { K: OUT, D: '#3a3a44', M: '#646470', L: '#d0d0dc', R: '#c0742a' },
  people_orchard: { K: OUT, D: '#3a6a2a', M: '#5f9a3a', L: '#d8f0b8', R: '#e08aa0' },
  // Explorer clubs — one heraldic hue each, distinct from the peoples.
  club_pathfinders: { K: OUT, D: '#2f5a3a', M: '#4f8a5a', L: '#f0e3a0' },
  club_armorers: { K: OUT, D: '#4a4a52', M: '#7a7a86', L: '#d8d8e0', R: '#b8362b' },
  club_mystics: { K: OUT, D: '#36286b', M: '#6a55ad', L: '#cdbfe2', R: '#a23fce' },
};

// Stable palette ref for a sprite key (undefined → theme ramp). Callers may
// spread per-instance tints on top: { ...spritePalette(k), ...variantTint(s) }.
export function spritePalette(key: SpriteKey): Record<string, string> | undefined {
  return SPRITE_PALETTES[key];
}

// ── Mapping helpers (keyword → sprite) ──────────────────────────────────────

export function classSpriteKey(className: string): SpriteKey {
  const c = (className || '').toLowerCase();
  if (/paladin|templar|crusader|guardian/.test(c)) return 'hero_paladin';
  if (/barbarian|berserk|warlord|brute|reaver/.test(c)) return 'hero_barbarian';
  if (/necro|death|reaper|lich|cultist/.test(c)) return 'hero_necromancer';
  if (/rogue|thief|assassin|duelist|burglar|cutpurse/.test(c)) return 'hero_rogue';
  if (/ranger|hunter|scout|archer|tracker|trapper/.test(c)) return 'hero_ranger';
  if (/mage|wizard|sorcer|witch|warlock|arcan|elementalist/.test(c)) return 'hero_mage';
  if (/druid|shaman|warden|geomancer/.test(c)) return 'hero_druid';
  if (/monk|martial|ascetic|brawler/.test(c)) return 'hero_monk';
  if (/bard|minstrel|skald|troubadour/.test(c)) return 'hero_bard';
  if (/cleric|priest|healer|oracle|acolyte/.test(c)) return 'hero_cleric';
  return 'hero_warrior';
}

export function enemySpriteKey(name: string): SpriteKey {
  const n = (name || '').toLowerCase();
  if (/spider|widow|weaver/.test(n)) return 'foe_spider';
  if (/wolf|dog|beast|boar|hound|warg|jackal/.test(n)) return 'foe_wolf';
  if (/golem|statue|construct|colossus|automaton/.test(n)) return 'foe_golem';
  if (/troll|ogre|guardian|treant|giant|brute/.test(n)) return 'foe_troll';
  if (/serpent|snake|naga|viper|drake|wyrm|wyvern/.test(n)) return 'foe_serpent';
  if (/imp|demon|fiend|devil|gremlin|hellion/.test(n)) return 'foe_imp';
  if (/cultist|acolyte|priest|warlock|sorcer|necro|zealot/.test(n)) return 'foe_cultist';
  if (/mimic|chest|hoard|trap/.test(n)) return 'foe_mimic';
  if (/skeleton|sentinel|crypt|bone|skull|undead/.test(n)) return 'foe_skeleton';
  if (/wraith|specter|spectre|ghost|phantom|shade|spirit/.test(n)) return 'foe_ghost';
  if (/slime|lurker|ooze|blob|gel/.test(n)) return 'foe_slime';
  if (/bat|scavenger|rat|swarm|vermin|pest/.test(n)) return 'foe_bat';
  return 'foe_bandit';
}

// Per-instance recolouring so duplicate foes / fallen allies in one view read as
// distinct individuals without authoring new art. Each variant hue-shifts the
// D/M shades within the theme accent ramp (K outline, L highlight and R accent
// stay so eyes/teeth read). Index 0 is the untinted base. Pure data.
export const VARIANT_TINTS: (Record<string, string> | undefined)[] = [
  undefined,
  { D: 'oklch(46% 0.11 calc(var(--accent-hue) + 45))', M: 'oklch(64% 0.11 calc(var(--accent-hue) + 45))' },
  { D: 'oklch(46% 0.11 calc(var(--accent-hue) - 45))', M: 'oklch(64% 0.11 calc(var(--accent-hue) - 45))' },
  { D: 'oklch(44% 0.10 calc(var(--accent-hue) + 110))', M: 'oklch(63% 0.10 calc(var(--accent-hue) + 110))' },
  { D: '#5a3a1f', M: '#a8793a' }, // earthen brown
  { D: '#3a4a5a', M: '#6a86a0' }, // slate blue
];

export function variantTint(seed: string): Record<string, string> | undefined {
  return VARIANT_TINTS[seedFrom(seed) % VARIANT_TINTS.length];
}

// Emblem shield for a people/culture id (see peoples.ts). Falls back to a
// villager sprite for any id without authored heraldry.
export function peopleSpriteKey(peopleId: string): SpriteKey {
  const k = `people_${peopleId}`;
  return SPRITES[k] ? k : 'npc_villager';
}

// Heraldic crest for an explorer club id (see meta.ts SPONSOR_IDS). Falls back
// to a banner prop for any id without authored heraldry.
export function clubSpriteKey(clubId: string): SpriteKey {
  const k = `club_${clubId}`;
  return SPRITES[k] ? k : 'prop_banner';
}

// Sprite shown on the world map for a node kind.
export function kindSpriteKey(kind: string): SpriteKey {
  switch (kind) {
    case 'town': return 'prop_tower';
    case 'village': return 'prop_house';
    case 'forest': return 'prop_tree';
    case 'wild': return 'prop_rock';
    case 'camp': return 'prop_fire';
    case 'dungeon': return 'prop_tomb';
    case 'cave': return 'prop_rock';
    case 'ruin': return 'prop_pillar';
    default: return 'prop_rock';
  }
}
