import { agentStream } from '../agent/agent';
import { getEffectiveModelId } from '../preferences/runtime-mode';
import { getPreferences } from '../preferences/preferences-service';
import { getChatConfig, type ChatKind } from './wa-chat-config';
import {
  recordMessage,
  upsertChatMeta,
  getRecentMessages,
  searchMessages,
  purgeOldMessages,
} from './wa-store';
import { readDir } from '@tauri-apps/plugin-fs';

const WA_URL = (import.meta as any).env?.VITE_WA_SIDECAR_URL || 'http://localhost:3472';
const SIDECAR_BASE = (import.meta as any).env?.VITE_SIDECAR_URL || 'http://localhost:3471';
const POLL_MS = 3000;
const HISTORY_RECENT = 8;          // verbatim tail
const HISTORY_OLDER_SUMMARIZED = 22; // older messages compressed into a system note
const HISTORY_TOTAL = HISTORY_RECENT + HISTORY_OLDER_SUMMARIZED;
const FTS_HITS = 3;
const BRIDGE_RUNTIME_VERSION = 'wa-bridge-v5';

// EU AI Act Article 50(1) — disclosure that the interlocutor is an AI system.
// Appended to outbound replies sent to third-party contacts (not to the user's
// own owner chat where AI-origin is already obvious).
const AI_DISCLOSURE_SUFFIX = '\n\n— Réponse assistée par IA (MonkeyAgent). / AI-assisted reply.';

function withAiDisclosure(text: string): string {
  const t = (text || '').trim();
  if (!t) return t;
  // Idempotent — never double-append if the model already included the marker.
  if (/AI-assisted|assisté par IA|assistée par IA|generated by AI/i.test(t)) return t;
  return `${t}${AI_DISCLOSURE_SUFFIX}`;
}

interface PendingApproval {
  id: string;
  sessionId: string;
  tool: string;
  title: string;
  summary: string;
}
const pendingApprovals = new Map<string, PendingApproval>();

function parseYesNo(text: string): 'yes' | 'no' | null {
  const t = text.trim().toLowerCase();
  if (/^(yes|y|ok|oui|o|allow|approve|go|👍|✅)\b/.test(t)) return 'yes';
  if (/^(no|n|non|deny|refuse|stop|cancel|👎|❌)\b/.test(t)) return 'no';
  return null;
}

interface InboxMsg { id: string; from: string; text: string; ts: number; kind?: ChatKind; }

export interface WhatsAppBridgeStatus {
  runtimeVersion: string;
  startedAt: string | null;
  running: boolean;
  queueLength: number;
  lastPollAt: string | null;
  lastPollCount: number;
  lastDequeuedAt: string | null;
  lastDequeuedId: string | null;
  lastDequeuedFrom: string | null;
  lastAgentStartAt: string | null;
  lastAgentDoneAt: string | null;
  lastAgentError: string | null;
  lastAgentPreview: string | null;
  lastApprovalAt: string | null;
  lastApprovalTool: string | null;
  lastApprovalDecision: string | null;
  lastSendAttemptAt: string | null;
  lastSendTarget: string | null;
  lastSendError: string | null;
}

// History now lives in Tauri SQLite (wa_message). Drop legacy LS rolls.
(function dropLegacyWaHistoryLS() {
  try {
    if (typeof localStorage === 'undefined') return;
    localStorage.removeItem('app.wa.chatHistory.v2');
    localStorage.removeItem('app.wa.chatHistory.v1');
    localStorage.removeItem('monkey.wa.chatHistory.v1');
  } catch {}
})();
let running = false;
let started = false;
let queue: InboxMsg[] = [];
let tickInFlight = false;

async function backfillFromSidecar() {
  try {
    const res = await fetch(`${WA_URL}/wa/chats`);
    if (!res.ok) return;
    const json = await res.json();
    const chats: Array<{ jid: string; name?: string }> = Array.isArray(json?.chats) ? json.chats : [];
    for (const c of chats) {
      if (!c?.jid) continue;
      await upsertChatMeta(c.jid, c.name || null);
      try {
        const hr = await fetch(`${WA_URL}/wa/history/${encodeURIComponent(c.jid)}?limit=${HISTORY_TOTAL}`);
        if (!hr.ok) continue;
        const hj = await hr.json();
        const messages: Array<{ id?: string; fromBot?: boolean; fromMe?: boolean; text: string; ts?: number }> =
          Array.isArray(hj?.messages) ? hj.messages : [];
        for (const m of messages) {
          if (!m || typeof m.text !== 'string' || !m.text.trim()) continue;
          const id = m.id || `bf_${c.jid}_${m.ts || 0}_${m.text.length}`;
          await recordMessage({
            id,
            jid: c.jid,
            fromBot: !!(m.fromBot ?? m.fromMe),
            text: m.text,
            ts: Number(m.ts) || Date.now(),
          }, c.name || null);
        }
        if (messages.length) logActivity('info', 'backfill', `[${c.jid.slice(-12)}] ${messages.length} msgs`);
      } catch {}
    }
  } catch {}
}

async function listContextFolderFiles(folder: string): Promise<string[]> {
  try {
    const entries = await readDir(folder);
    return entries
      .filter((e: any) => !e.isDirectory && typeof e.name === 'string' && e.name && !e.name.startsWith('.'))
      .map((e: any) => e.name as string)
      .sort();
  } catch {
    return [];
  }
}

function buildContextFolderBlock(files: string[]): string {
  if (!files.length) return '';
  const sample = files.slice(0, 40);
  return [
    '[AVAILABLE DOCUMENTS — files in the user-configured context folder for this chat]',
    ...sample.map(n => `- ${n}`),
    files.length > sample.length ? `(+${files.length - sample.length} more)` : '',
    'To send one of these documents to the user via WhatsApp, write `[SEND_DOC: <exact filename>]` on its own line in your reply.',
    'The bridge will strip the marker and send the file as a WhatsApp document attachment. Only filenames from the list above are valid; never invent paths.',
    '[END AVAILABLE DOCUMENTS]',
  ].filter(Boolean).join('\n');
}

const SEND_DOC_RE = /\[SEND_DOC:\s*([^\]\n]+?)\s*\]/g;

function extractSendDocDirectives(text: string, allowed: Set<string>): { cleaned: string; files: string[] } {
  const files: string[] = [];
  const cleaned = text.replace(SEND_DOC_RE, (_, raw: string) => {
    const name = String(raw).trim();
    if (!name || name.includes('/') || name.includes('\\') || name === '..' || name === '.') return '';
    if (!allowed.has(name)) return '';
    if (!files.includes(name)) files.push(name);
    return '';
  }).replace(/\n{3,}/g, '\n\n').trim();
  return { cleaned, files };
}

function joinPath(folder: string, name: string): string {
  const sep = folder.includes('\\') && !folder.includes('/') ? '\\' : '/';
  return folder.endsWith(sep) ? folder + name : folder + sep + name;
}

async function sendDocument(to: string, folder: string, filename: string): Promise<boolean> {
  const abs = joinPath(folder, filename);
  try {
    const res = await fetch(`${WA_URL}/wa/send-file`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ to, path: abs, kind: 'document', filename }),
    });
    if (!res.ok) {
      const detail = await res.text().catch(() => '');
      logActivity('error', 'send-doc', `→ ${to} ${filename}: HTTP ${res.status} ${detail}`.trim());
      return false;
    }
    logActivity('info', 'send-doc', `→ ${to} ${filename}`);
    const ts = Date.now();
    const id = `outdoc_${to}_${ts}_${Math.random().toString(36).slice(2, 10)}`;
    try { await recordMessage({ id, jid: to, fromBot: true, text: `[document: ${filename}]`, ts }); } catch {}
    return true;
  } catch (e) {
    logActivity('error', 'send-doc', `→ ${to} ${filename}: ${e instanceof Error ? e.message : String(e)}`);
    return false;
  }
}

function summarizeOlder(older: Array<{ role: string; content: string }>): string {
  if (!older.length) return '';
  const lines = older.map(m => {
    const who = m.role === 'assistant' ? 'Bot' : 'User';
    const text = m.content.replace(/\s+/g, ' ').trim();
    const trimmed = text.length > 200 ? text.slice(0, 199) + '…' : text;
    return `- ${who}: ${trimmed}`;
  });
  return [
    '[PAST CONVERSATION — already happened, do not re-answer, use only for context]',
    `Older exchanges with this chat (oldest first, ${older.length} message(s)):`,
    ...lines,
    '[END PAST CONVERSATION]',
  ].join('\n');
}

const bridgeStatus: WhatsAppBridgeStatus = {
  runtimeVersion: BRIDGE_RUNTIME_VERSION,
  startedAt: null,
  running: false,
  queueLength: 0,
  lastPollAt: null,
  lastPollCount: 0,
  lastDequeuedAt: null,
  lastDequeuedId: null,
  lastDequeuedFrom: null,
  lastAgentStartAt: null,
  lastAgentDoneAt: null,
  lastAgentError: null,
  lastAgentPreview: null,
  lastApprovalAt: null,
  lastApprovalTool: null,
  lastApprovalDecision: null,
  lastSendAttemptAt: null,
  lastSendTarget: null,
  lastSendError: null,
};

function syncBridgeStatus(patch: Partial<WhatsAppBridgeStatus> = {}) {
  Object.assign(bridgeStatus, patch);
  bridgeStatus.running = running;
  bridgeStatus.queueLength = queue.length;
}

export function getWhatsAppBridgeStatus(): WhatsAppBridgeStatus {
  return { ...bridgeStatus, running, queueLength: queue.length };
}

export interface WhatsAppActivityEvent {
  id: number;
  at: string;
  level: 'info' | 'warn' | 'error';
  tag: string;
  message: string;
}

const ACTIVITY_MAX = 200;
let activityCounter = 0;
const activityLog: WhatsAppActivityEvent[] = [];
const activityListeners = new Set<(events: WhatsAppActivityEvent[]) => void>();

function logActivity(level: WhatsAppActivityEvent['level'], tag: string, message: string) {
  const ev: WhatsAppActivityEvent = {
    id: ++activityCounter,
    at: new Date().toISOString(),
    level, tag, message,
  };
  activityLog.push(ev);
  if (activityLog.length > ACTIVITY_MAX) activityLog.splice(0, activityLog.length - ACTIVITY_MAX);
  const snapshot = activityLog.slice();
  for (const fn of activityListeners) { try { fn(snapshot); } catch {} }
}

export function getWhatsAppActivity(): WhatsAppActivityEvent[] {
  return activityLog.slice();
}

export function pushWhatsAppActivity(level: WhatsAppActivityEvent['level'], tag: string, message: string) {
  logActivity(level, tag, message);
}

export function subscribeWhatsAppActivity(fn: (events: WhatsAppActivityEvent[]) => void): () => void {
  activityListeners.add(fn);
  fn(activityLog.slice());
  return () => { activityListeners.delete(fn); };
}

async function fetchInbox(): Promise<InboxMsg[]> {
  syncBridgeStatus({ lastPollAt: new Date().toISOString() });
  try {
    const res = await fetch(`${WA_URL}/wa/inbox`);
    if (!res.ok) {
      syncBridgeStatus({ lastPollCount: 0 });
      logActivity('warn', 'poll', `inbox HTTP ${res.status}`);
      return [];
    }
    const json = await res.json();
    const messages = Array.isArray(json?.messages) ? json.messages : [];
    syncBridgeStatus({ lastPollCount: messages.length });
    if (messages.length) logActivity('info', 'poll', `${messages.length} message(s) reçus`);
    return messages;
  } catch (e) {
    syncBridgeStatus({ lastPollCount: 0 });
    logActivity('error', 'poll', `inbox fetch failed: ${e instanceof Error ? e.message : String(e)}`);
    return [];
  }
}

const SEND_MAX_ATTEMPTS = 3;

async function sendReply(to: string, text: string) {
  syncBridgeStatus({
    lastSendAttemptAt: new Date().toISOString(),
    lastSendTarget: to,
    lastSendError: null,
  });
  let lastError = '';
  for (let attempt = 1; attempt <= SEND_MAX_ATTEMPTS; attempt++) {
    try {
      const res = await fetch(`${WA_URL}/wa/send`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ to, message: text }),
      });
      if (res.ok) {
        logActivity('info', 'send', `→ ${to} (${text.length} chars)${attempt > 1 ? ` [attempt ${attempt}]` : ''}`);
        const ts = Date.now();
        const id = `out_${to}_${ts}_${Math.random().toString(36).slice(2, 10)}`;
        try { await recordMessage({ id, jid: to, fromBot: true, text, ts }); } catch {}
        return;
      }
      const detail = await res.text().catch(() => '');
      lastError = `HTTP ${res.status} ${detail}`.trim();
      // 409 not_ready = sidecar reconnecting (transient) → retry.
      // Other 4xx = permanent (bad jid, etc.) → give up immediately.
      if (res.status !== 409 && res.status < 500) break;
    } catch (error) {
      // Network error: sidecar restarting → retry.
      lastError = error instanceof Error ? error.message : String(error);
    }
    if (attempt < SEND_MAX_ATTEMPTS) await new Promise(r => setTimeout(r, 2000 * attempt));
  }
  syncBridgeStatus({ lastSendError: lastError });
  logActivity('error', 'send', `→ ${to}: ${lastError}`);
  console.warn(`[wa-bridge] send failed to ${to}: ${lastError}`);
}

async function postApproval(id: string, decision: 'allow' | 'deny', scope: 'once' | 'session', sessionId: string, toolName: string) {
  syncBridgeStatus({
    lastApprovalAt: new Date().toISOString(),
    lastApprovalTool: toolName || null,
    lastApprovalDecision: decision,
  });
  try {
    await fetch(`${SIDECAR_BASE}/approve`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ id, decision, scope, session_id: sessionId, tool: toolName }),
    });
  } catch (error) {
    syncBridgeStatus({
      lastAgentError: `approval ${decision} failed: ${error instanceof Error ? error.message : String(error)}`,
    });
  }
}

async function handleApprovalRequest(chatId: string, ev: any) {
  const id = ev.id;
  const sessionId = `whatsapp:${chatId}`;
  const tool = ev.tool || ev.name || '';
  const bypass = !!ev.bypass;
  if (!bypass) {
    // Safe sensitive tool (run_command in workspace, delete_file, web search, etc.) → auto-allow for session.
    logActivity('info', 'approval', `auto-allow ${tool}`);
    await postApproval(id, 'allow', 'session', sessionId, tool);
    return;
  }
  // Dangerous pattern → ask user via WhatsApp.
  const title = ev.title || `Approve ${tool}?`;
  const summary = ev.summary || '';
  pendingApprovals.set(chatId, { id, sessionId, tool, title, summary });
  const prompt = `⚠️ ${title}\n${summary}\n\nReply YES to allow once, or NO to deny.`;
  logActivity('warn', 'approval', `ask user ${tool}: ${title}`);
  await sendReply(chatId, prompt);
}

async function runAgentOnce(chatId: string, text: string, kind: ChatKind): Promise<{ reply: string; docs: string[]; folder: string }> {
  const config = getChatConfig(chatId, kind);
  const contextFolder = (config.contextFolder || '').trim();
  const folderFiles = contextFolder ? await listContextFolderFiles(contextFolder) : [];
  const folderBlock = folderFiles.length ? buildContextFolderBlock(folderFiles) : '';

  // Pull the full window from SQLite (already includes the inbound user msg recorded in tick()).
  const persisted = await getRecentMessages(chatId, HISTORY_TOTAL);
  const mapped = persisted
    .filter(m => m.text && m.text.trim())
    .map(m => ({ role: m.fromBot ? 'assistant' : 'user', content: m.text }));
  const recent = mapped.slice(-HISTORY_RECENT);
  const older = mapped.slice(0, Math.max(0, mapped.length - HISTORY_RECENT));
  const summaryBlock = summarizeOlder(older);

  // Ensure the current user text is the last message even if persistence was
  // skipped (race) — agent must always see what it's answering.
  const last = recent[recent.length - 1];
  if (!(last && last.role === 'user' && last.content === text)) {
    recent.push({ role: 'user', content: text });
    if (recent.length > HISTORY_RECENT) recent.splice(0, recent.length - HISTORY_RECENT);
  }

  // FTS hits (semantic-ish recall) — only for contact persona where we want the
  // bot to surface old facts the user might reference implicitly.
  let ftsBlock = '';
  if (kind === 'contact') {
    try {
      const hits = await searchMessages(chatId, text, FTS_HITS);
      if (hits.length) {
        ftsBlock = [
          '[RELEVANT PAST MESSAGES — keyword matches from this chat history]',
          ...hits.map(h => {
            const who = h.fromBot ? 'Bot' : 'User';
            const t = h.text.replace(/\s+/g, ' ').trim();
            return `- ${who}: ${t.length > 200 ? t.slice(0, 199) + '…' : t}`;
          }),
          '[END RELEVANT PAST MESSAGES]',
        ].join('\n');
      }
    } catch {}
  }

  const personaParts = [summaryBlock, ftsBlock, folderBlock, kind === 'contact' ? (config.persona || '') : '']
    .filter(s => s && s.trim());
  const extraSystemInstructions = personaParts.length ? personaParts.join('\n\n') : undefined;

  const modelId = getEffectiveModelId();
  const prefs = getPreferences();
  logActivity('info', 'model', modelId ? `model=${modelId}` : 'model=auto (no selection)');
  if (older.length || ftsBlock) {
    logActivity('info', 'history', `[${chatId.slice(-12)}] recent=${recent.length} summarized=${older.length} fts=${ftsBlock ? FTS_HITS : 0}`);
  }

  let finalText = '';
  let deltaBuf = '';
  syncBridgeStatus({
    lastAgentStartAt: new Date().toISOString(),
    lastAgentDoneAt: null,
    lastAgentError: null,
    lastAgentPreview: text.slice(0, 160),
  });
  logActivity('info', 'agent', `[${chatId.slice(-12)}] ${text.slice(0, 80)}${text.length > 80 ? '…' : ''}`);

  // Watchdog: a hung agent (model stall, dead sidecar stream) would leave
  // running=true forever and block the whole queue. Abort after 3min of
  // stream silence — except while waiting for a user approval over WhatsApp
  // (legitimately slow), where the window stretches to 15min. Hard cap 20min.
  const AGENT_INACTIVITY_MS = 180_000;
  const AGENT_APPROVAL_WAIT_MS = 900_000;
  const AGENT_TOTAL_MS = 1_200_000;
  const abort = new AbortController();
  const agentStartedAt = Date.now();
  let timedOut = false;
  let inactivityMs = AGENT_INACTIVITY_MS;
  const onTimeout = () => { timedOut = true; abort.abort(); };
  let watchdog = setTimeout(onTimeout, inactivityMs);
  const petWatchdog = () => {
    clearTimeout(watchdog);
    const remaining = AGENT_TOTAL_MS - (Date.now() - agentStartedAt);
    if (remaining <= 0) { onTimeout(); return; }
    watchdog = setTimeout(onTimeout, Math.min(inactivityMs, remaining));
  };

  try {
    for await (const ev of agentStream({
      messages: recent.slice(),
      modelId: modelId || undefined,
      imageModelId: prefs.imageModelId || undefined,
      preferredFamily: prefs.agentModelFamily || undefined,
      budgetMode: prefs.agentModelBudgetMode,
      allowFamilyFallback: prefs.allowAgentFamilyFallback,
      sessionId: `whatsapp:${chatId}`,
      extraSystemInstructions,
      toolMode: 'full',
      contextFolder: contextFolder || undefined,
      signal: abort.signal,
    })) {
      inactivityMs = ev.type === 'approval_request' ? AGENT_APPROVAL_WAIT_MS : AGENT_INACTIVITY_MS;
      petWatchdog();
      if (ev.type === 'token' && typeof ev.content === 'string') deltaBuf += ev.content;
      else if (ev.type === 'approval_request') {
        await handleApprovalRequest(chatId, ev);
      }
      else if (ev.type === 'aborted') {
        break;
      }
      else if (ev.type === 'done') {
        if (typeof ev.data === 'string' && ev.data.trim()) finalText = ev.data;
        break;
      } else if (ev.type === 'error') {
        finalText = `(monkey error: ${ev.message || 'unknown'})`;
        syncBridgeStatus({ lastAgentError: ev.message || 'unknown' });
        logActivity('error', 'agent', ev.message || 'unknown');
        break;
      } else if (ev.type === 'tool_start') {
        const args = ev.args ? ` ${JSON.stringify(ev.args).slice(0, 80)}` : '';
        logActivity('info', 'tool', `▶ ${ev.name || '?'}${args}`);
      } else if (ev.type === 'tool_done') {
        const out = typeof ev.result === 'string' ? ` → ${ev.result.slice(0, 80)}` : '';
        logActivity('info', 'tool', `✓ ${ev.name || '?'}${out}`);
      } else if (ev.type === 'model_route') {
        if (ev.message) logActivity('info', 'route', String(ev.message).slice(0, 120));
      }
    }
  } catch (e: any) {
    if (!timedOut) {
      finalText = `(monkey error: ${e?.message || e})`;
      syncBridgeStatus({ lastAgentError: e?.message || String(e) });
    }
  } finally {
    clearTimeout(watchdog);
  }

  if (timedOut && !finalText) {
    finalText = deltaBuf.trim() || '(monkey error: agent timed out)';
    syncBridgeStatus({ lastAgentError: 'agent stream timed out' });
    logActivity('error', 'agent', `[${chatId.slice(-12)}] stream timed out after ${Math.round((Date.now() - agentStartedAt) / 1000)}s`);
  }
  if (!finalText) finalText = deltaBuf.trim() || '(pas de réponse)';
  // Strip [SEND_DOC: filename] markers, return the list to caller.
  const allowed = new Set(folderFiles);
  const { cleaned, files } = folderFiles.length
    ? extractSendDocDirectives(finalText, allowed)
    : { cleaned: finalText, files: [] as string[] };
  // Outbound persistence happens in sendReply() — no separate write here.
  syncBridgeStatus({ lastAgentDoneAt: new Date().toISOString() });
  logActivity('info', 'done', `${cleaned.length} chars${files.length ? ` + ${files.length} doc(s)` : ''}`);
  return { reply: cleaned || '(pas de réponse)', docs: files, folder: contextFolder };
}

async function drainQueue() {
  if (running) return;
  running = true;
  syncBridgeStatus();
  try {
    while (queue.length) {
      const msg = queue.shift()!;
      syncBridgeStatus({
        lastDequeuedAt: new Date().toISOString(),
        lastDequeuedId: msg.id,
        lastDequeuedFrom: msg.from,
      });
      const kind: ChatKind = msg.kind === 'contact' ? 'contact' : 'owner';
      logActivity('info', 'dequeue', `[${msg.from.slice(-12)}] (${kind}) ${msg.text.slice(0, 60)}${msg.text.length > 60 ? '…' : ''}`);
      try {
        const { reply, docs, folder } = await runAgentOnce(msg.from, msg.text, kind);
        // EU AI Act Art. 50(1): outbound to a third-party contact must disclose AI.
        // Owner chat = the user talking to themselves → already obvious, no disclosure.
        const outbound = kind === 'contact' ? withAiDisclosure(reply) : reply;
        await sendReply(msg.from, outbound);
        for (const name of docs) {
          await sendDocument(msg.from, folder, name);
        }
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        syncBridgeStatus({ lastAgentError: message });
        logActivity('error', 'agent', `[${msg.from.slice(-12)}] run failed: ${message}`);
        const fallback = kind === 'contact'
          ? withAiDisclosure("Désolé, erreur temporaire. Renvoie ton message.")
          : "Désolé, erreur temporaire. Renvoie ton message.";
        await sendReply(msg.from, fallback);
      }
      syncBridgeStatus();
    }
  } finally {
    running = false;
    syncBridgeStatus();
  }
}

async function tick() {
  if (tickInFlight) return;
  tickInFlight = true;
  try {
    const msgs = await fetchInbox();
    if (!msgs.length) return;
    for (const msg of msgs) {
      // Persist EVERY inbound, before any gating, so history survives restarts
      // even when the agent is muted on a contact.
      try {
        await recordMessage({
          id: msg.id,
          jid: msg.from,
          fromBot: false,
          text: msg.text,
          ts: msg.ts || Date.now(),
        });
      } catch {}
      const pending = pendingApprovals.get(msg.from);
      if (pending) {
        const ans = parseYesNo(msg.text);
        if (ans) {
          pendingApprovals.delete(msg.from);
          const decision = ans === 'yes' ? 'allow' : 'deny';
          logActivity('info', 'approval', `user ${decision} ${pending.tool}`);
          await postApproval(pending.id, decision, 'once', pending.sessionId, pending.tool);
          await sendReply(msg.from, decision === 'allow' ? '✅ Approved.' : '❌ Denied.');
          continue;
        }
        // Not a yes/no — remind and keep pending.
        await sendReply(msg.from, `Pending approval: ${pending.title}\nReply YES or NO.`);
        continue;
      }
      const kind: ChatKind = msg.kind === 'contact' ? 'contact' : 'owner';
      if (kind === 'contact') {
        const cfg = getChatConfig(msg.from, 'contact');
        if (!cfg.agentEnabled) {
          logActivity('info', 'gate', `contact agent off → skip [${msg.from.slice(-12)}]`);
          continue;
        }
      }
      // Keep strict message order: enqueue one message then drain immediately.
      // This guarantees each reply is generated against the right "current"
      // inbound message, even when multiple user messages arrive in one poll.
      queue.push(msg);
      syncBridgeStatus();
      try {
        await drainQueue();
      } catch (error) {
        syncBridgeStatus({
          lastAgentError: error instanceof Error ? error.message : String(error),
        });
      }
    }
  } finally {
    tickInFlight = false;
  }
}

const seenJobRuns = new Set<string>();
const seenJobStarts = new Set<string>();
// Per-task: last (runStartedAt, log length) we emitted. Lets us forward only
// new runLog entries as the job streams steps, without re-emitting the whole
// log on every poll.
const seenJobLog = new Map<string, { startedAt: string; count: number }>();
let jobPollFirstRun = true;

async function pollScheduledJobs() {
  try {
    const { api } = await import('../api');
    const tasks = await api.getTasks();
    for (const t of tasks) {
      if (!t.agentPrompt) continue;
      if (t.runStartedAt && !t.runFinishedAt) {
        const key = `start:${t.id}:${t.runStartedAt}`;
        if (!seenJobStarts.has(key)) {
          seenJobStarts.add(key);
          if (!jobPollFirstRun) logActivity('info', 'job', `▶ ${t.title} — démarré`);
        }
      }
      // Stream new runLog entries (intent/tool_start/tool_done/model/error)
      // between start and done.
      const log = t.runLog || [];
      if (t.runStartedAt && log.length > 0) {
        const prev = seenJobLog.get(t.id);
        const startedAt = String(t.runStartedAt);
        const startFresh = !prev || prev.startedAt !== startedAt;
        const from = startFresh ? 0 : prev!.count;
        if (!jobPollFirstRun) {
          for (let i = from; i < log.length; i++) {
            const e = log[i];
            const level = e.kind === 'error' ? 'error' : 'info';
            const detail = e.detail ? ` — ${e.detail.slice(0, 120)}` : '';
            logActivity(level, 'job', `[${t.title}] ${e.kind}: ${e.label}${detail}`);
          }
        }
        seenJobLog.set(t.id, { startedAt, count: log.length });
      }
      if (t.runFinishedAt && t.runResult) {
        const key = `done:${t.id}:${t.runFinishedAt}`;
        if (!seenJobRuns.has(key)) {
          seenJobRuns.add(key);
          if (!jobPollFirstRun) {
            const isErr = t.runResult.startsWith('ERREUR:');
            const preview = t.runResult.length > 140 ? t.runResult.slice(0, 137) + '…' : t.runResult;
            logActivity(isErr ? 'error' : 'info', 'job', `${isErr ? '✖' : '✓'} ${t.title} — ${preview}`);
          }
        }
      }
    }
    jobPollFirstRun = false;
  } catch {}
}

export function startWhatsAppBridge() {
  if (started) return;
  started = true;
  syncBridgeStatus({ startedAt: new Date().toISOString() });
  logActivity('info', 'bridge', `démarré (${BRIDGE_RUNTIME_VERSION})`);
  void purgeOldMessages().catch(() => {});
  void backfillFromSidecar().catch(() => {});
  tick().catch(() => {});
  setInterval(tick, POLL_MS);
  void pollScheduledJobs();
  setInterval(() => { void pollScheduledJobs(); }, 5000);
}
