"""Agent tools for IMAP/SMTP mailboxes.

All tools call `mail_store` / `imap_client` / `smtp_client` directly (same
process as the sidecar). Errors are returned with the `ERREUR:` prefix so the
deterministic gate in agent.py can react. Outputs are JSON strings for
structured results.
"""
from __future__ import annotations
import json
import re
import time
from typing import Any

from monkey import mail_store, imap_client, smtp_client

# EU AI Act Article 50(1) — disclose AI-assisted origin in every outbound mail.
# Bilingual EN/FR. Idempotent: skipped when the body already mentions AI assistance.
_AI_DISCLOSURE_TEXT = (
    "\n\n— Réponse assistée par IA (Monkey). / AI-assisted reply.\n"
    "(EU AI Act Article 50 — vous pouvez répondre pour interagir avec un humain.)"
)
_AI_DISCLOSURE_HTML = (
    '<hr><p style="font-size:0.85em;color:#666">'
    "— Réponse assistée par IA (Monkey). / AI-assisted reply.<br>"
    "<em>EU AI Act Article 50 — vous pouvez répondre pour interagir avec un humain.</em>"
    "</p>"
)
_AI_MARK_RE = re.compile(r"AI-assisted|assist[ée]e? par IA|generated by AI", re.IGNORECASE)


def _append_ai_disclosure_text(body: str) -> str:
    if not body:
        return _AI_DISCLOSURE_TEXT.strip()
    if _AI_MARK_RE.search(body):
        return body
    return body.rstrip() + _AI_DISCLOSURE_TEXT


def _append_ai_disclosure_html(html: str) -> str:
    if not html:
        return _AI_DISCLOSURE_HTML
    if _AI_MARK_RE.search(html):
        return html
    return html + _AI_DISCLOSURE_HTML


# Cache of detected special folders per account_id. TTL ~5min keeps the IMAP
# LIST roundtrip out of the hot path while letting users rename folders.
_SPECIAL_TTL = 300
_special_cache: dict[str, tuple[float, dict]] = {}


def _special_folders(account: dict, password: str) -> dict:
    aid = account["id"]
    cached = _special_cache.get(aid)
    now = time.time()
    if cached and (now - cached[0]) < _SPECIAL_TTL:
        return cached[1]
    sp = imap_client.detect_special_folders(account, password)
    _special_cache[aid] = (now, sp)
    return sp


_NEWSLETTER_FROM_RE = re.compile(
    r"(?i)\b(?:noreply|no-reply|do-?not-?reply|donotreply|notifications?|alerts?|"
    r"newsletter|mailer|news@|info@|hello@|team@|contact@|support@|updates?@|"
    r"marketing@|hi@|bonjour@|nepasrepondre)\b"
)
_PROMO_SUBJECT_RE = re.compile(
    r"(?i)\b(?:unsubscribe|d[ée]sinscri|promo|sale|soldes?|newsletter|"
    r"weekly|digest|recap|résum[eé]|view in browser|voir dans le navigateur)\b"
)
_SPAMMY_SUBJECT_RE = re.compile(
    r"(?i)\b(?:viagra|winner|lottery|claim your|free crypto|forex|nigerian prince|"
    r"héritage|congratulations you|prince of|reclam[eé] votre)\b"
)


def _classify(msg: dict, *, now_ts: int) -> tuple[str, str]:
    """Return (action, reason). action ∈ {keep, archive, trash, review}."""
    flags = msg.get("flags") or []
    seen = "\\Seen" in flags
    flagged = "\\Flagged" in flags
    from_h = (msg.get("from") or "").lower()
    subject = msg.get("subject") or ""
    age_days = max(0, (now_ts - int(msg.get("dateTs") or now_ts)) // (1000 * 86400))

    if _SPAMMY_SUBJECT_RE.search(subject):
        return ("trash", "spam-like subject")
    if flagged:
        return ("keep", "user-flagged")
    if _NEWSLETTER_FROM_RE.search(from_h) or _PROMO_SUBJECT_RE.search(subject):
        if age_days > 30 and not seen:
            return ("trash", "old unread newsletter (>30d)")
        return ("archive", "newsletter/notification")
    if seen:
        return ("archive", "already read")
    if age_days > 14:
        return ("archive", "unread but stale (>14d)")
    return ("review", "recent unread human-looking mail")


def _slim_account(a: dict) -> dict:
    return {
        "id": a["id"],
        "label": a["label"],
        "email": a["email"],
        "indexInKb": bool(a.get("indexInKb")),
        "lastUid": int(a.get("lastUid") or 0),
        "lastError": a.get("lastError") or "",
    }


def _slim_message(m: dict, *, with_body: bool = False) -> dict:
    out = {
        "id": m["id"],
        "accountId": m["accountId"],
        "uid": m["uid"],
        "folder": m.get("folder", "INBOX"),
        "from": m.get("from", ""),
        "to": m.get("to") or [],
        "subject": m.get("subject", ""),
        "dateTs": m.get("dateTs", 0),
        "flags": m.get("flags") or [],
        "hasAttachments": bool(m.get("hasAttachments")),
        "unread": "\\Seen" not in (m.get("flags") or []),
    }
    if with_body:
        body = m.get("bodyText") or ""
        if len(body) > 6000:
            body = body[:6000] + "\n…[truncated]"
        out["bodyText"] = body
    return out


def mail_list_accounts() -> str:
    accs = [_slim_account(a) for a in mail_store.list_accounts()]
    if not accs:
        return "OK: no mail account configured"
    return json.dumps(accs, ensure_ascii=False)


def _server_inbox_scan(account_id: str, limit: int) -> list[dict] | None:
    """Try a live IMAP scan for account_id's INBOX. Returns slim messages or
    None on any failure (caller falls back to local store)."""
    if not account_id:
        return None
    account = mail_store.get_account(account_id)
    if not account:
        return None
    password = mail_store.get_password(account_id)
    if not password:
        return None
    env = imap_client.fetch_envelopes(
        account, password, folder="INBOX", max_messages=limit, newest_first=True,
    )
    if not env.get("ok"):
        return None
    out: list[dict] = []
    for e in env.get("messages") or []:
        out.append({
            "id": f"imap-{account_id}-{e['uid']}",
            "uid": int(e["uid"]),
            "from": e.get("from", ""),
            "subject": e.get("subject", ""),
            "dateTs": int(e.get("dateTs") or 0),
            "flags": e.get("flags") or [],
            "folder": "INBOX",
            "accountId": account_id,
        })
    return out


def mail_unread_count(account_id: str = "") -> str:
    """Count unread messages in INBOX. Queries IMAP directly (truth) when
    account_id is provided; falls back to the local cache otherwise."""
    aid = (account_id or "").strip()
    if aid:
        account = mail_store.get_account(aid)
        password = mail_store.get_password(aid) if account else ""
        if account and password:
            try:
                import imaplib
                cfg = account["imap"]
                cli = imap_client._connect(cfg["host"], cfg["port"], cfg.get("socket") or "SSL")
                try:
                    cli.login(account["email"], password)
                    cli.select("INBOX", readonly=True)
                    typ, data = cli.uid("SEARCH", None, "UNSEEN")
                    typ2, data2 = cli.uid("SEARCH", None, "ALL")
                    if typ == "OK" and typ2 == "OK":
                        unread = len((data[0] or b"").split())
                        total = len((data2[0] or b"").split())
                        return json.dumps({"accountId": aid, "unread": unread, "inboxTotal": total, "source": "imap"}, ensure_ascii=False)
                finally:
                    try: cli.logout()
                    except Exception: pass
            except Exception:
                pass
    n = mail_store.unread_count(account_id=aid or None)
    return json.dumps({"accountId": aid or None, "unread": int(n), "source": "local"}, ensure_ascii=False)


def mail_list(account_id: str = "", folder: str = "INBOX",
              limit: int = 30, unread_only: bool = False) -> str:
    """List messages. For INBOX, queries IMAP directly so it sees the full
    server state (not just locally-synced messages). Other folders fall back
    to the local cache."""
    aid = (account_id or "").strip() or None
    limit = max(1, min(int(limit or 30), 100))
    folder = folder or "INBOX"
    if aid and folder.upper() == "INBOX":
        live = _server_inbox_scan(aid, limit)
        if live is not None:
            if unread_only:
                live = [m for m in live if "\\Seen" not in (m.get("flags") or [])]
            return json.dumps(live[:limit], ensure_ascii=False)
    msgs = mail_store.list_messages(
        account_id=aid, folder=folder,
        limit=limit, offset=0, unread_only=bool(unread_only),
    )
    return json.dumps([_slim_message(m) for m in msgs], ensure_ascii=False)


def mail_search(query: str, account_id: str = "", limit: int = 20) -> str:
    q = (query or "").strip()
    if not q:
        return "ERREUR: mail_search requires query"
    aid = (account_id or "").strip() or None
    limit = max(1, min(int(limit or 20), 50))
    hits = mail_store.search_messages(q, account_id=aid, limit=limit)
    if not hits:
        return "OK: no match in local mail index"
    return json.dumps([_slim_message(m) for m in hits], ensure_ascii=False)


def mail_read(message_id: str) -> str:
    mid = (message_id or "").strip()
    if not mid:
        return "ERREUR: mail_read requires message_id"
    m = mail_store.get_message(mid, with_html=False)
    if not m:
        return f"ERREUR: message not found: {mid}"
    return json.dumps(_slim_message(m, with_body=True), ensure_ascii=False)


def mail_sync(account_id: str, max_messages: int = 200) -> str:
    aid = (account_id or "").strip()
    if not aid:
        return "ERREUR: mail_sync requires account_id"
    account = mail_store.get_account(aid)
    if not account:
        return f"ERREUR: account not found: {aid}"
    password = mail_store.get_password(aid)
    if not password:
        return f"ERREUR: no password in keychain for {account['email']}"
    max_n = max(1, min(int(max_messages or 200), 1000))
    result = imap_client.sync_inbox(
        account, password, max_messages=max_n, last_uid=account["lastUid"],
    )
    if not result["ok"]:
        mail_store.set_sync_state(aid, last_error=result["error"])
        return f"ERREUR: sync failed: {result['error']}"
    inserted = 0
    for msg in result["messages"]:
        if mail_store.insert_message(aid, msg):
            inserted += 1
    mail_store.set_sync_state(aid, last_uid=result["new_last_uid"], last_error="")
    return json.dumps({
        "ok": True,
        "fetched": result["fetched"],
        "inserted": inserted,
        "newLastUid": result["new_last_uid"],
    }, ensure_ascii=False)


def mail_send(account_id: str, to: list[str], subject: str = "", body: str = "",
              cc: list[str] | None = None, bcc: list[str] | None = None,
              in_reply_to: str = "", references: str = "",
              html: str = "") -> str:
    aid = (account_id or "").strip()
    if not aid:
        return "ERREUR: mail_send requires account_id"
    account = mail_store.get_account(aid)
    if not account:
        return f"ERREUR: account not found: {aid}"
    password = mail_store.get_password(aid)
    if not password:
        return f"ERREUR: no password in keychain for {account['email']}"
    if not to or not isinstance(to, list):
        return "ERREUR: mail_send requires non-empty `to` list"
    from monkey.main import _sanitize_outgoing
    # EU AI Act Article 50(1) — disclose AI-assisted origin to the recipient.
    # Idempotent: do not double-append if the body already mentions AI assistance.
    sanitized_body = _sanitize_outgoing(body or "")
    body_with_disclosure = _append_ai_disclosure_text(sanitized_body)
    html_with_disclosure = _append_ai_disclosure_html(html) if html else None
    ok, err, raw = smtp_client.send(
        account, password,
        to=[str(x) for x in to],
        subject=subject or "",
        body=body_with_disclosure,
        cc=[str(x) for x in (cc or [])],
        bcc=[str(x) for x in (bcc or [])],
        in_reply_to=in_reply_to or None,
        references=references or None,
        html=html_with_disclosure,
    )
    if not ok:
        return f"ERREUR: send failed: {err}"
    append_status: dict[str, Any] = {"attempted": False}
    if raw:
        sent_folder = _special_folders(account, password).get("sent") or "Sent"
        append_status = {"attempted": True, "folder": sent_folder}
        try:
            ok_app, err_app = imap_client.append_sent(account, password, raw, folder=sent_folder)
            append_status["ok"] = bool(ok_app)
            if not ok_app:
                append_status["error"] = err_app
        except Exception as e:
            append_status["ok"] = False
            append_status["error"] = str(e)
    return json.dumps({"ok": True, "to": to, "subject": subject, "sentAppend": append_status}, ensure_ascii=False)


def _resolve_msg(message_id: str) -> tuple[dict | None, dict | None, str]:
    mid = (message_id or "").strip()
    if not mid:
        return None, None, "ERREUR: requires message_id"
    # Live IMAP id format: "imap-<accountId>-<uid>". Built by mail_list /
    # mail_summarize_inbox when reading from the server. We synthesize a
    # minimal msg dict so the existing action tools can operate.
    if mid.startswith("imap-"):
        rest = mid[len("imap-"):]
        # accountId may contain '-'; uid is the trailing digits after the last '-'
        idx = rest.rfind("-")
        if idx <= 0:
            return None, None, f"ERREUR: bad imap id: {mid}"
        aid = rest[:idx]
        try:
            uid = int(rest[idx + 1:])
        except ValueError:
            return None, None, f"ERREUR: bad imap id: {mid}"
        account = mail_store.get_account(aid)
        if not account:
            return None, None, f"ERREUR: account not found: {aid}"
        return ({"id": mid, "accountId": aid, "uid": uid, "folder": "INBOX", "flags": []}, account, "")
    msg = mail_store.get_message(mid, with_html=False)
    if not msg:
        return None, None, f"ERREUR: message not found: {mid}"
    account = mail_store.get_account(msg["accountId"])
    if not account:
        return None, None, f"ERREUR: account missing for message: {mid}"
    return msg, account, ""


def mail_flag(message_id: str, flag: str = "\\Seen", remove: bool = False) -> str:
    msg, account, err = _resolve_msg(message_id)
    if err:
        return err
    password = mail_store.get_password(account["id"])
    if not password:
        return f"ERREUR: no password in keychain for {account['email']}"
    flag = (flag or "").strip() or "\\Seen"
    ok, ferr = imap_client.set_flag(
        account, password, int(msg["uid"]), flag,
        remove=bool(remove), folder=msg.get("folder") or "INBOX",
    )
    if not ok:
        return f"ERREUR: flag failed: {ferr}"
    flags = list(msg.get("flags") or [])
    if remove:
        flags = [f for f in flags if f != flag]
    elif flag not in flags:
        flags.append(flag)
    mail_store.update_flags(msg["id"], flags)
    return json.dumps({"ok": True, "id": msg["id"], "flag": flag, "removed": bool(remove)}, ensure_ascii=False)


def mail_move(message_id: str, dest_folder: str) -> str:
    msg, account, err = _resolve_msg(message_id)
    if err:
        return err
    dest = (dest_folder or "").strip()
    if not dest:
        return "ERREUR: mail_move requires dest_folder"
    password = mail_store.get_password(account["id"])
    if not password:
        return f"ERREUR: no password in keychain for {account['email']}"
    ok, ferr = imap_client.move_to(
        account, password, int(msg["uid"]), dest,
        folder=msg.get("folder") or "INBOX",
    )
    if not ok:
        return f"ERREUR: move failed: {ferr}"
    return json.dumps({"ok": True, "id": msg["id"], "dest": dest}, ensure_ascii=False)


def mail_archive(message_id: str, folder: str = "") -> str:
    """Move a message to the account's Archive folder. Auto-detects per server
    (Gmail → [Gmail]/All Mail). Pass `folder` to override."""
    msg, account, err = _resolve_msg(message_id)
    if err:
        return err
    password = mail_store.get_password(account["id"])
    if not password:
        return f"ERREUR: no password in keychain for {account['email']}"
    dest = (folder or "").strip()
    if not dest:
        sp = _special_folders(account, password)
        dest = sp.get("archive") or sp.get("all") or "Archive"
    return mail_move(message_id, dest)


def mail_delete(message_id: str) -> str:
    """Move a message to Trash (auto-detected per server)."""
    msg, account, err = _resolve_msg(message_id)
    if err:
        return err
    password = mail_store.get_password(account["id"])
    if not password:
        return f"ERREUR: no password in keychain for {account['email']}"
    sp = _special_folders(account, password)
    dest = sp.get("trash") or "Trash"
    return mail_move(message_id, dest)


def mail_label_add(message_id: str, label: str) -> str:
    """Add a label to a message without removing it from its current folder.
    On Gmail uses X-GM-LABELS (true labels). On other IMAP servers does an
    additive COPY to the target folder (message keeps INBOX presence)."""
    msg, account, err = _resolve_msg(message_id)
    if err:
        return err
    lbl = (label or "").strip()
    if not lbl:
        return "ERREUR: mail_label_add requires label"
    password = mail_store.get_password(account["id"])
    if not password:
        return f"ERREUR: no password in keychain for {account['email']}"
    sp = _special_folders(account, password)
    folder = msg.get("folder") or "INBOX"
    if sp.get("isGmail"):
        ok, ferr = imap_client.gmail_labels(
            account, password, int(msg["uid"]), [lbl], remove=False, folder=folder,
        )
    else:
        ok, ferr = imap_client.copy_to(
            account, password, int(msg["uid"]), lbl, folder=folder,
        )
    if not ok:
        return f"ERREUR: label add failed: {ferr}"
    return json.dumps({"ok": True, "id": msg["id"], "label": lbl, "gmail": bool(sp.get("isGmail"))}, ensure_ascii=False)


def mail_label_remove(message_id: str, label: str) -> str:
    """Remove a Gmail label from a message. On non-Gmail servers this is a
    no-op (labels are not first-class — use mail_move instead)."""
    msg, account, err = _resolve_msg(message_id)
    if err:
        return err
    lbl = (label or "").strip()
    if not lbl:
        return "ERREUR: mail_label_remove requires label"
    password = mail_store.get_password(account["id"])
    if not password:
        return f"ERREUR: no password in keychain for {account['email']}"
    sp = _special_folders(account, password)
    if not sp.get("isGmail"):
        return json.dumps({"ok": False, "id": msg["id"], "reason": "not_gmail_no_labels"}, ensure_ascii=False)
    ok, ferr = imap_client.gmail_labels(
        account, password, int(msg["uid"]), [lbl], remove=True,
        folder=msg.get("folder") or "INBOX",
    )
    if not ok:
        return f"ERREUR: label remove failed: {ferr}"
    return json.dumps({"ok": True, "id": msg["id"], "label": lbl, "removed": True}, ensure_ascii=False)


def mail_list_folders(account_id: str) -> str:
    aid = (account_id or "").strip()
    if not aid:
        return "ERREUR: mail_list_folders requires account_id"
    account = mail_store.get_account(aid)
    if not account:
        return f"ERREUR: account not found: {aid}"
    password = mail_store.get_password(aid)
    if not password:
        return f"ERREUR: no password in keychain for {account['email']}"
    folders, err = imap_client.list_folders(account, password)
    if err:
        return f"ERREUR: list folders failed: {err}"
    sp = _special_folders(account, password)
    return json.dumps({"folders": folders, "special": sp}, ensure_ascii=False)


def mail_reply(message_id: str, body: str, html: str = "",
               quote_original: bool = True, reply_all: bool = False) -> str:
    """Reply to a message. Auto-fills To/Subject/In-Reply-To/References from
    the original. Set reply_all=True to include Cc + other To recipients."""
    msg, account, err = _resolve_msg(message_id)
    if err:
        return err
    password = mail_store.get_password(account["id"])
    if not password:
        return f"ERREUR: no password in keychain for {account['email']}"

    sender = msg.get("from") or ""
    m = re.search(r"<([^>]+)>", sender)
    sender_addr = (m.group(1) if m else sender).strip()
    if not sender_addr:
        return "ERREUR: cannot determine reply address from original message"

    to_list = [sender_addr]
    cc_list: list[str] = []
    if reply_all:
        own = (account.get("email") or "").lower()
        for addr in msg.get("to") or []:
            a = str(addr).strip()
            if a and a.lower() != own and a.lower() != sender_addr.lower():
                to_list.append(a)
        for addr in msg.get("cc") or []:
            a = str(addr).strip()
            if a and a.lower() != own:
                cc_list.append(a)

    subj = msg.get("subject") or ""
    if not re.match(r"^\s*re\s*:", subj, re.I):
        subj = f"Re: {subj}".strip()

    orig_mid = (msg.get("messageId") or "").strip()
    in_reply_to = f"<{orig_mid}>" if orig_mid and not orig_mid.startswith("<") else orig_mid
    thread_root = (msg.get("threadId") or "").strip()
    root_fmt = f"<{thread_root}>" if thread_root and not thread_root.startswith("<") else thread_root
    refs_parts = [p for p in (root_fmt, in_reply_to) if p]
    seen_parts: list[str] = []
    for p in refs_parts:
        if p not in seen_parts:
            seen_parts.append(p)
    refs = " ".join(seen_parts)

    final_body = body or ""
    if quote_original:
        quoted = (msg.get("bodyText") or "")[:4000]
        quoted = "\n".join("> " + line for line in quoted.splitlines())
        final_body = f"{final_body}\n\nOn {time.strftime('%Y-%m-%d %H:%M', time.localtime((msg.get('dateTs') or 0)/1000))}, {sender} wrote:\n{quoted}"

    return mail_send(
        account["id"], to=to_list, subject=subj, body=final_body,
        cc=cc_list or None, in_reply_to=in_reply_to, references=refs, html=html or "",
    )


def mail_clean_inbox(account_id: str, mode: str = "safe",
                     dry_run: bool = True, batch_size: int = 25,
                     preview_limit: int = 100) -> str:
    """Triage INBOX using best-practice heuristics. Processes ONE BATCH per call.

    Workflow:
      1. First call with dry_run=true → returns the plan for the next
         `preview_limit` messages (no server-side change). Use to confirm.
      2. Then call repeatedly with dry_run=false → each call processes up to
         `batch_size` messages in a single IMAP session and returns a progress
         report. Keep calling while `done=false`.

    Actions per message:
      - keep    : flagged (\\Flagged) — stays in INBOX
      - archive : already read OR newsletter/notification OR stale unread
      - trash   : spam-like subject OR very old unread newsletter
      - review  : recent unread human-looking mail

    Modes:
      - safe       : applies archive/trash only; review stays in INBOX
      - aggressive : applies archive/trash AND archives review (inbox zero)

    Response includes `done` (true when no more actionable messages remain),
    `remainingInbox`, and `actionable` (msgs left that this mode WOULD process).
    """
    aid = (account_id or "").strip()
    if not aid:
        return "ERREUR: mail_clean_inbox requires account_id"
    account = mail_store.get_account(aid)
    if not account:
        return f"ERREUR: account not found: {aid}"
    password = mail_store.get_password(aid)
    if not password:
        return f"ERREUR: no password in keychain for {account['email']}"
    mode = (mode or "safe").lower()
    if mode not in ("safe", "aggressive"):
        return "ERREUR: mode must be 'safe' or 'aggressive'"
    batch_size = max(1, min(int(batch_size or 25), 100))
    preview_limit = max(1, min(int(preview_limit or 100), 500))

    now_ts = int(time.time() * 1000)
    sp = _special_folders(account, password)
    archive_folder = sp.get("archive") or sp.get("all") or "Archive"
    trash_folder = sp.get("trash") or "Trash"

    def classify_all(msgs: list[dict]) -> list[dict]:
        out: list[dict] = []
        for m in msgs:
            action, reason = _classify(m, now_ts=now_ts)
            if action == "review" and mode == "aggressive":
                action, reason = "archive", f"aggressive: {reason}"
            out.append({
                "id": m["id"], "uid": int(m["uid"]),
                "from": m.get("from", ""), "subject": m.get("subject", ""),
                "dateTs": int(m.get("dateTs") or 0),
                "action": action, "reason": reason,
                "dest": archive_folder if action == "archive" else (trash_folder if action == "trash" else ""),
            })
        return out

    # Server-side scan: pull UID+FLAGS+headers directly from IMAP. The local
    # SQLite cache only holds the newest 200 from the last mail_sync, which is
    # useless for inboxes with thousands of messages. Scan the newest portion
    # of the mailbox each call — once items get moved out, the next call sees
    # the next slice.
    def server_scan(limit: int) -> tuple[list[dict], int]:
        env = imap_client.fetch_envelopes(
            account, password, folder="INBOX", max_messages=limit, newest_first=True,
        )
        if not env.get("ok"):
            return ([], 0)
        msgs = []
        for e in env.get("messages") or []:
            msgs.append({
                "id": f"imap-{e['uid']}", "uid": int(e["uid"]),
                "from": e.get("from", ""), "subject": e.get("subject", ""),
                "dateTs": int(e.get("dateTs") or 0),
                "flags": e.get("flags") or [],
            })
        return (msgs, int(env.get("total") or 0))

    # ── DRY RUN — single shot, just preview the plan ────────────────────────
    if dry_run:
        msgs, inbox_total = server_scan(preview_limit)
        plan = classify_all(msgs)
        counts = {"keep": 0, "archive": 0, "trash": 0, "review": 0}
        for p in plan:
            counts[p["action"]] = counts.get(p["action"], 0) + 1
        return json.dumps({
            "ok": True, "dryRun": True, "mode": mode,
            "inboxTotal": inbox_total,
            "previewed": len(msgs),
            "counts": counts,
            "archiveFolder": archive_folder, "trashFolder": trash_folder,
            "plan": plan,
            "hint": "Call again with dry_run=false to apply. Loop until done=true.",
        }, ensure_ascii=False)

    # ── APPLY — process one batch in a single IMAP session ──────────────────
    # Walk newest INBOX UIDs until we collect `batch_size` actionable msgs.
    scan_limit = batch_size * 4
    scanned, inbox_total_initial = server_scan(scan_limit)
    scan_plan = classify_all(scanned)

    moves: list[dict] = []
    in_batch: list[dict] = []
    counts = {"keep": 0, "archive": 0, "trash": 0, "review": 0, "skipped": 0}
    for p in scan_plan:
        if p["action"] in ("keep", "review"):
            counts[p["action"]] += 1
            continue
        if len(moves) >= batch_size:
            break
        moves.append({"uid": p["uid"], "dest": p["dest"]})
        in_batch.append(p)
        counts[p["action"]] += 1

    if not moves:
        # Nothing to do in the scanned window. If scan covered the whole inbox
        # (scanned >= total) we're truly done; otherwise widen the scan.
        if len(scanned) >= inbox_total_initial:
            done_flag = True
            actionable_remaining = 0
        else:
            wider, _ = server_scan(min(inbox_total_initial, 1000))
            actionable_remaining = sum(
                1 for p in classify_all(wider) if p["action"] not in ("keep", "review")
            )
            done_flag = actionable_remaining == 0
        return json.dumps({
            "ok": True, "dryRun": False, "mode": mode,
            "batch": {"size": 0, "archived": 0, "trashed": 0, "errors": []},
            "scanned": len(scanned),
            "counts": counts,
            "remainingInbox": inbox_total_initial,
            "actionable": actionable_remaining,
            "done": done_flag,
            "elapsedMs": 0,
        }, ensure_ascii=False)

    res = imap_client.move_many(account, password, moves, folder="INBOX")
    # Drop applied msgs from local cache so we don't re-process them. Best
    # effort: rows stay in the DB until the next mail_sync, but updating the
    # folder field shifts them out of INBOX queries.
    errored_uids = {int(e.get("uid") or 0) for e in res.get("errors", [])}
    archived = 0
    trashed = 0
    for p in in_batch:
        if int(p["uid"]) in errored_uids:
            continue
        try:
            mail_store.update_folder(p["id"], p["dest"])
        except AttributeError:
            pass
        if p["action"] == "archive":
            archived += 1
        else:
            trashed += 1

    # New total = old total minus successful moves.
    moved_ok = archived + trashed
    remaining_inbox = max(0, inbox_total_initial - moved_ok)
    # Heuristic: if we filled a full batch, there's likely more actionable.
    actionable_remaining = remaining_inbox if len(moves) >= batch_size else 0

    return json.dumps({
        "ok": True, "dryRun": False, "mode": mode,
        "batch": {
            "size": len(moves),
            "archived": archived,
            "trashed": trashed,
            "errors": res.get("errors", []),
        },
        "scanned": len(scanned),
        "counts": counts,
        "archiveFolder": archive_folder, "trashFolder": trash_folder,
        "remainingInbox": remaining_inbox,
        "actionable": actionable_remaining,
        "done": remaining_inbox == 0 or (len(moves) < batch_size and actionable_remaining == 0),
        "elapsedMs": int(res.get("elapsedMs") or 0),
    }, ensure_ascii=False)


def mail_summarize_inbox(account_id: str = "", limit: int = 20) -> str:
    """Return a compact INBOX summary. Queries IMAP directly when possible so
    the totals match what Gmail/server actually shows (not just the local cache)."""
    aid = (account_id or "").strip() or None
    limit = max(1, min(int(limit or 20), 50))
    if aid:
        account = mail_store.get_account(aid)
        password = mail_store.get_password(aid) if account else ""
        if account and password:
            env = imap_client.fetch_envelopes(
                account, password, folder="INBOX", max_messages=limit, newest_first=True,
            )
            if env.get("ok"):
                items = []
                for e in env.get("messages") or []:
                    items.append({
                        "id": f"imap-{aid}-{e['uid']}",
                        "uid": int(e["uid"]),
                        "from": e.get("from", ""),
                        "subject": e.get("subject", ""),
                        "dateTs": int(e.get("dateTs") or 0),
                        "flags": e.get("flags") or [],
                    })
                unread = sum(1 for m in items if "\\Seen" not in (m.get("flags") or []))
                return json.dumps({
                    "accountId": aid,
                    "inboxTotal": int(env.get("total") or 0),
                    "shown": len(items),
                    "unreadInShown": unread,
                    "source": "imap",
                    "items": items,
                }, ensure_ascii=False)
    msgs = mail_store.list_messages(account_id=aid, folder="INBOX", limit=limit, offset=0)
    if not msgs:
        return "OK: inbox empty (local cache; provide account_id for live IMAP)"
    unread = sum(1 for m in msgs if "\\Seen" not in (m.get("flags") or []))
    return json.dumps({
        "accountId": aid,
        "total": len(msgs),
        "unread": unread,
        "source": "local",
        "items": [_slim_message(m) for m in msgs],
    }, ensure_ascii=False)
