ALTER TABLE "ModelMeta" ADD COLUMN "family" TEXT;
ALTER TABLE "ModelMeta" ADD COLUMN "sizeB" DOUBLE PRECISION;
ALTER TABLE "ModelMeta" ADD COLUMN "activeB" DOUBLE PRECISION;
ALTER TABLE "ModelMeta" ADD COLUMN "task" TEXT;
ALTER TABLE "ModelMeta" ADD COLUMN "minVramGb" INTEGER;
ALTER TABLE "ModelMeta" ADD COLUMN "license" TEXT;
